/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

// 4 import files (SQLException,logging.Level,logging.Logger,JOptionPane)
//new Added files==>> import Data.Validator; || import java.sql.ResultSet; || import java.math.BigDecimal; || import java.sql.SQLException; || import javax.swing.table.DefaultTableModel;
import DATA.Deliverydetails;
import Data.DBConnManager;
import Data.DB_Access;
import Data.Validator;
import IReports.IReports;
import IReports.IReports;
import gui.EmpMng.Home;
import gui.Selling;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oshani
 */
public class Charge extends javax.swing.JFrame {

    boolean result;
    DB_Access dba = new DB_Access();
    DBConnManager dbm = new DBConnManager();
    // [01] .. Delivery_Agent ********************************************************
    int agentId;
    String name;
    String company;
    String location;
    String phone;
    float chargingRate;
    int rating;
    //  [02] .. Order_Delivery**********************************************************
    int cusOrderID;
    double deliveryCost;
    String handoverDate;
    int tripKM;
   

    public Charge() {
        initComponents();
      
        filAgentId2();
        filAgentId3();
        filAgentId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_AgentID = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jTextField_Company = new javax.swing.JTextField();
        jTextField_Location = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_AddAgent = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_AgentName = new javax.swing.JTextField();
        jButton_Delete = new javax.swing.JButton();
        jButton_FindBestCourier = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jButton_Demo1 = new javax.swing.JButton();
        jButton_ViewAll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ChargingRate = new javax.swing.JTextField();
        jButton_ViewReports = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel = new javax.swing.JPanel();
        jTextField_TripKM = new javax.swing.JTextField();
        jTextField_DeliveryCharge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_CalculateCharge = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_SeachCustID = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_AgentID = new javax.swing.JComboBox();
        jButton_RefreshOrder = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_CusOrderID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_HandOverDate = new javax.swing.JTextField();
        jButton_ClearAll = new javax.swing.JButton();
        jButton_AddOrder = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton_DeleteOrd = new javax.swing.JButton();
        jButton_UpdateOrd = new javax.swing.JButton();
        jButton_Demo3 = new javax.swing.JButton();
        jButton_ViewAllOr = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton_home = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_SearchAgntID = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_ArgentID1 = new javax.swing.JComboBox();
        jButton_RefreshCourier = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton_home1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery Management");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Delivery Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 170, 230, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Delivery Agent ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Agent Name ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 86, 30);

        jTextField_AgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgentIDActionPerformed(evt);
            }
        });
        jTextField_AgentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_AgentIDFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_AgentID);
        jTextField_AgentID.setBounds(112, 27, 140, 30);

        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_PhoneFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_Phone);
        jTextField_Phone.setBounds(110, 157, 140, 30);

        jTextField_Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CompanyActionPerformed(evt);
            }
        });
        jTextField_Company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CompanyFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_Company);
        jTextField_Company.setBounds(110, 109, 140, 30);

        jTextField_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LocationActionPerformed(evt);
            }
        });
        jTextField_Location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LocationFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_Location);
        jTextField_Location.setBounds(110, 196, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Phone         ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 157, 68, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Location      ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 195, 71, 30);

        jButton_AddAgent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AddAgent.setText("Add Agent");
        jButton_AddAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddAgentActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_AddAgent);
        jButton_AddAgent.setBounds(303, 28, 100, 30);

        jButton_Clear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Clear);
        jButton_Clear.setBounds(304, 184, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Charging Rate");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(6, 240, 73, 30);

        jTextField_AgentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgentNameActionPerformed(evt);
            }
        });
        jTextField_AgentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_AgentNameFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_AgentName);
        jTextField_AgentName.setBounds(110, 69, 140, 30);

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton_DeleteFocusGained(evt);
            }
        });
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Delete);
        jButton_Delete.setBounds(304, 145, 100, 30);

        jButton_FindBestCourier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_FindBestCourier.setText("Find Best Courier");
        jButton_FindBestCourier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FindBestCourierActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_FindBestCourier);
        jButton_FindBestCourier.setBounds(260, 230, 140, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Company  ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 113, 72, 20);
        jLabel17.getAccessibleContext().setAccessibleName("Company         ");

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Update);
        jButton_Update.setBounds(303, 70, 100, 30);

        jButton_Demo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo1.setText("Demo1");
        jButton_Demo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Demo1);
        jButton_Demo1.setBounds(440, 30, 80, 30);

        jButton_ViewAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ViewAll.setText("View All");
        jButton_ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewAllActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_ViewAll);
        jButton_ViewAll.setBounds(304, 109, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Agent ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 30, 80, 20);

        jTextField_ChargingRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_ChargingRateFocusLost(evt);
            }
        });
        jPanel2.add(jTextField_ChargingRate);
        jTextField_ChargingRate.setBounds(110, 238, 140, 30);

        jButton_ViewReports.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ViewReports.setText("View Invoice");
        jButton_ViewReports.setActionCommand("View Report");
        jButton_ViewReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewReportsActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_ViewReports);
        jButton_ViewReports.setBounds(410, 230, 140, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 190, 560, 290);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(140, 42, 750, 0);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Delivery Order", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jPanel.setLayout(null);

        jTextField_TripKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TripKMActionPerformed(evt);
            }
        });
        jTextField_TripKM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_TripKMFocusLost(evt);
            }
        });
        jPanel.add(jTextField_TripKM);
        jTextField_TripKM.setBounds(160, 110, 140, 30);

        jTextField_DeliveryCharge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_DeliveryCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DeliveryChargeActionPerformed(evt);
            }
        });
        jPanel.add(jTextField_DeliveryCharge);
        jTextField_DeliveryCharge.setBounds(220, 240, 80, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Rs :");
        jPanel.add(jLabel8);
        jLabel8.setBounds(170, 240, 45, 34);

        jButton_CalculateCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CalculateCharge.setText("Calculate Charge");
        jButton_CalculateCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalculateChargeActionPerformed(evt);
            }
        });
        jPanel.add(jButton_CalculateCharge);
        jButton_CalculateCharge.setBounds(20, 240, 140, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Trip Km                   ");
        jPanel.add(jLabel7);
        jLabel7.setBounds(20, 110, 121, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(null);

        jTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer OrderID", "Agent ID", "trip KM", "Delivery Cost", "Hand Over Date"
            }
        ));
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable2FocusGained(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 525, 100);

        jButton_SeachCustID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_SeachCustID.setText("Search");
        jButton_SeachCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SeachCustIDActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_SeachCustID);
        jButton_SeachCustID.setBounds(340, 110, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel15.setText("Customer Order ID   ");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(50, 110, 103, 30);
        jLabel15.getAccessibleContext().setAccessibleName("Customer Order ID ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel16.setText("Agent ID           ");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(50, 150, 78, 23);

        jComboBox_AgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AgentIDActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox_AgentID);
        jComboBox_AgentID.setBounds(180, 150, 140, 30);

        jButton_RefreshOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_RefreshOrder.setText("Refresh");
        jButton_RefreshOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshOrderActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_RefreshOrder);
        jButton_RefreshOrder.setBounds(340, 150, 100, 30);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(180, 110, 140, 30);

        jPanel.add(jPanel5);
        jPanel5.setBounds(10, 290, 530, 200);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Customer Order ID    ");
        jPanel.add(jLabel12);
        jLabel12.setBounds(20, 70, 121, 31);

        jTextField_CusOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CusOrderIDActionPerformed(evt);
            }
        });
        jTextField_CusOrderID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CusOrderIDFocusLost(evt);
            }
        });
        jPanel.add(jTextField_CusOrderID);
        jTextField_CusOrderID.setBounds(160, 70, 140, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Hand Over Date     ");
        jPanel.add(jLabel13);
        jLabel13.setBounds(20, 160, 109, 28);

        jTextField_HandOverDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HandOverDateActionPerformed(evt);
            }
        });
        jPanel.add(jTextField_HandOverDate);
        jTextField_HandOverDate.setBounds(160, 160, 140, 30);

        jButton_ClearAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ClearAll.setText("Clear");
        jButton_ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearAllActionPerformed(evt);
            }
        });
        jPanel.add(jButton_ClearAll);
        jButton_ClearAll.setBounds(320, 200, 100, 30);

        jButton_AddOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AddOrder.setText("Add Order");
        jButton_AddOrder.setActionCommand("Add ");
        jButton_AddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOrderActionPerformed(evt);
            }
        });
        jPanel.add(jButton_AddOrder);
        jButton_AddOrder.setBounds(320, 30, 100, 30);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setText("Select Date");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel.add(jButton12);
        jButton12.setBounds(160, 200, 140, 29);

        jButton_DeleteOrd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_DeleteOrd.setText("Delete");
        jButton_DeleteOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteOrdActionPerformed(evt);
            }
        });
        jPanel.add(jButton_DeleteOrd);
        jButton_DeleteOrd.setBounds(320, 160, 100, 30);

        jButton_UpdateOrd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_UpdateOrd.setText("Update");
        jButton_UpdateOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateOrdActionPerformed(evt);
            }
        });
        jPanel.add(jButton_UpdateOrd);
        jButton_UpdateOrd.setBounds(320, 70, 100, 30);

        jButton_Demo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo3.setText("Demo3");
        jButton_Demo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Demo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo3ActionPerformed(evt);
            }
        });
        jPanel.add(jButton_Demo3);
        jButton_Demo3.setBounds(430, 30, 80, 30);

        jButton_ViewAllOr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ViewAllOr.setText("View All");
        jButton_ViewAllOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewAllOrActionPerformed(evt);
            }
        });
        jPanel.add(jButton_ViewAllOr);
        jButton_ViewAllOr.setBounds(320, 110, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Agent ID");
        jPanel.add(jLabel14);
        jLabel14.setBounds(20, 40, 100, 15);

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel.add(jComboBox4);
        jComboBox4.setBounds(160, 30, 140, 30);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        jPanel.add(jButton_home);
        jButton_home.setBounds(1220, 630, 50, 35);

        getContentPane().add(jPanel);
        jPanel.setBounds(570, 190, 545, 500);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Agent ID", "Agent Name", "Company", "Phone", "Location", "ChargingRate", "Rate"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_SearchAgntID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_SearchAgntID.setText("Search");
        jButton_SearchAgntID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchAgntIDActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton14.setText("Clear");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel18.setText("Agent ID");

        jComboBox_ArgentID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ArgentID1ActionPerformed(evt);
            }
        });

        jButton_RefreshCourier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_RefreshCourier.setText("Resresh");
        jButton_RefreshCourier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshCourierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(35, 35, 35)
                .addComponent(jComboBox_ArgentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_SearchAgntID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_RefreshCourier, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox_ArgentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SearchAgntID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_RefreshCourier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2527, 2527, 2527))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 480, 570, 210);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 0, 1280, 150);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1300, 160);

        jButton_home1.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_home1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home1);
        jButton_home1.setBounds(1220, 630, 50, 35);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1130, 160, 170, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_AgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgentIDActionPerformed

    private void jTextField_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LocationActionPerformed

    private void jButton_AddAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddAgentActionPerformed


        if (jTextField_AgentID.getText().isEmpty() || jTextField_AgentName.getText().isEmpty() || jTextField_Phone.getText().isEmpty() || jTextField_Company.getText().isEmpty() || jTextField_Location.getText().isEmpty() || jTextField_ChargingRate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill Texts", "Error", 0);
        } else {

            agentId = Integer.parseInt(jTextField_AgentID.getText());
            name = jTextField_AgentName.getText();
            company = jTextField_Company.getText();
            location = jTextField_Location.getText();
            phone = jTextField_Phone.getText();
            chargingRate = Float.parseFloat(jTextField_ChargingRate.getText());
            rating = 1;


            // [01] .. Insert [ ADD ] data into Delivery_Agent TABLE  ...................................

            try {


                Deliverydetails dc = new Deliverydetails(agentId, name, company, location, phone, chargingRate, rating);
                boolean result = dc.addAgent();

                if (result) {
                    JOptionPane.showMessageDialog(this, "Insertion Successful!");
                } else {
                    JOptionPane.showMessageDialog(this, "Insertion Failure!");
                }


                ResultSet rs = dba.getData("select * from delivery_agent where agentId='" + agentId + "'");

                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                int row = dtm.getRowCount();

                for (int i = 0; i < row; i++) {
                    dtm.removeRow(0);
                }

                while (rs.next()) {
                    Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                    dtm.addRow(ob);
                }

                JOptionPane.showMessageDialog(this, "Insert delivery details Successful!");

                //surround statement with try catch..................................................................
            } catch (SQLException ex) {
                System.out.println(ex + "Errrrrrrrrrrrrr");
                //  Logger.getLogger(Charge.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Errror in Inserting!");

            }
        }




    }//GEN-LAST:event_jButton_AddAgentActionPerformed

    private void jButton_FindBestCourierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FindBestCourierActionPerformed
        // TODO add your handling code here:

        //**********Go to Find Best courier GUI*************
        //AND DISABLE THIS CHARGE WINDO===>DISPOSE

        Bestcouriers bc = new Bestcouriers();
        bc.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton_FindBestCourierActionPerformed

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jTextField_CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CompanyActionPerformed

    private void jTextField_AgentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgentNameActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed


        jTextField_ChargingRate.setText("");
        jTextField_AgentID.setText("");
        jTextField_AgentName.setText("");
        jTextField_Phone.setText("");
        jTextField_Company.setText("");
        jTextField_Location.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int row = jTable1.getSelectedRow();

        if (jTable1.getRowSelectionAllowed()) {

            jTextField_AgentID.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jComboBox_ArgentID1.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

            jTextField_AgentName.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jTextField_Company.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jTextField_Phone.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());

            jTextField_Location.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());

            jTextField_ChargingRate.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());

        }

        jTextField_AgentID.setEnabled(false);
        // jTextField1.setEnabled(false);



    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:

        //        name = jTextField10.getText();

        String agentId = jComboBox_ArgentID1.getSelectedItem().toString();



        try {


            dba.setData("delete from delivery_agent where  agentId='" + agentId + "'");

            ResultSet rst = dba.getData("select * from delivery_agent");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }

            while (rst.next()) {
                Object ob[] = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5), rst.getString(6), rst.getString(7)};
                dtm.addRow(ob);
            }

            JOptionPane.showMessageDialog(this, "Successfully Deleted!");

        } catch (SQLException ex) {
           
            
            System.out.println(ex + "Errrrrrrrrrrrr");
            JOptionPane.showMessageDialog(this, "Error in Deleting. Cannot deleteagent row first delete delivery order !!!");
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_DeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton_DeleteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteFocusGained

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        // jButton10.setEnabled(true);
    }//GEN-LAST:event_jTable1FocusGained

    private void jButton_SearchAgntIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchAgntIDActionPerformed
        // TODO add your handling code here:

        String agentId = jComboBox_ArgentID1.getSelectedItem().toString();


        //Add import for DB_Access
        try {
            ResultSet rs = dba.getData("select * from delivery_agent  where agentId='" + agentId + "' ");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int row = dtm.getRowCount();
            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }
            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                dtm.addRow(ob);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "SQL Error", "Error", 0);

        }


    }//GEN-LAST:event_jButton_SearchAgntIDActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
//        jTextField10.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        agentId = Integer.parseInt(jTextField_AgentID.getText());
        name = jTextField_AgentName.getText();
        company = jTextField_Company.getText();
        location = jTextField_Location.getText();
        phone = jTextField_Phone.getText();
        chargingRate = Float.parseFloat(jTextField_ChargingRate.getText());


        try {

            Deliverydetails dc = new Deliverydetails(agentId, name, company, location, phone, chargingRate, rating);
            boolean result = dc.updateAgent();

            if (result) {
                JOptionPane.showMessageDialog(this, "Update Successful!");
            } else {
                JOptionPane.showMessageDialog(this, "Update Failure!");
            }

            ResultSet rs = dba.getData("select * from delivery_agent ");

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }

            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                dtm.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Charge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        jTextField_AgentID.setEnabled(true);
        jTextField_AgentName.setEnabled(true);
        jTextField_Phone.setEnabled(true);
        jTextField_Company.setEnabled(true);
        jTextField_Location.setEnabled(true);



        jTextField_HandOverDate.setEnabled(true);
        jTextField_TripKM.setEnabled(true);
        jTextField_AgentID.setEnabled(true);
        jTextField_DeliveryCharge.setEnabled(true);


    }//GEN-LAST:event_formWindowOpened

    private void jButton_UpdateOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateOrdActionPerformed
        // TODO add your handling code here:


        String agentId = jComboBox4.getSelectedItem().toString();
        tripKM = Integer.parseInt(jTextField_TripKM.getText());
        cusOrderID = Integer.parseInt(jTextField_CusOrderID.getText());
        deliveryCost = Double.parseDouble(jTextField_DeliveryCharge.getText());
        handoverDate = jTextField_HandOverDate.getText();



        try {
            dba.setData("update order_delivery set cusOrderID='" + cusOrderID + "', agentId='" + agentId + "',tripKM='" + tripKM + "',deliveryCost='" + deliveryCost + "',handoverDate='" + handoverDate + "' where  agentId='" + agentId + "'AND cusOrderID='" + cusOrderID + "'");
            JOptionPane.showMessageDialog(this, "Successfully Updated!");

            ResultSet rs = dba.getData("select * from order_delivery ");

            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }

            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                dtm.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Charge.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_UpdateOrdActionPerformed

    private void jButton_DeleteOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteOrdActionPerformed
        // TODO add your handling code here:

     

       // String cusOrderID = jComboBox_CusOrID.getSelectedItem().toString();
         String agentId = jComboBox_AgentID.getSelectedItem().toString();
         cusOrderID = Integer.parseInt(jTextField1.getText());
         
        try {
            //Deleting Delivery_Agent Details********************************************

            dba.setData("delete from order_delivery  where agentId='" + agentId + "'AND cusOrderID='" + cusOrderID + "'");
            ResultSet rst = dba.getData("select * from order_delivery ");
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }

            while (rst.next()) {
                Object ob[] = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5)};
                dtm.addRow(ob);
            }

            JOptionPane.showMessageDialog(this, "Successfully Deleted!");

        } catch (SQLException ex) {
           
            
            System.out.println(ex + "Errrrrrrrrrrrr");
            JOptionPane.showMessageDialog(this, "Error in Deleting!");
        }

    }//GEN-LAST:event_jButton_DeleteOrdActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        gui.DatePicker datePicker = new gui.DatePicker(this);
        jTextField_HandOverDate.setText(datePicker.setPickedDate());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton_AddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOrderActionPerformed

        // TODO add your handling code here

        if (jTextField_ChargingRate.getText().isEmpty() || jTextField_TripKM.getText().isEmpty() || jTextField_DeliveryCharge.getText().isEmpty() || jTextField_HandOverDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill Texts", "Error", 0);
        } else {

            String agentId = jComboBox4.getSelectedItem().toString();

            tripKM = Integer.parseInt(jTextField_TripKM.getText());
            cusOrderID = Integer.parseInt(jTextField_CusOrderID.getText());
            deliveryCost = Double.parseDouble(jTextField_DeliveryCharge.getText());
            handoverDate = jTextField_HandOverDate.getText();

            // [01] .. Insert [ ADD ] data into order_delivery TABLE  ...................................

            try {
                dba.setData("insert into order_delivery(cusOrderID,agentId,tripKM ,deliveryCost ,handoverDate) "
                        + "values ('" + cusOrderID + "','" + agentId + "','" + tripKM + "','" + deliveryCost + "','" + handoverDate + "')");



                ResultSet rs = dba.getData("select * from order_delivery where agentId='" + agentId + "'AND cusOrderID='" + cusOrderID + "'");

                DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
                int row = dtm.getRowCount();

                for (int i = 0; i < row; i++) {
                    dtm.removeRow(0);
                }

                while (rs.next()) {
                    Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                    dtm.addRow(ob);
                }

                JOptionPane.showMessageDialog(this, "Insert delivery details Successful!");

                //surround statement with try catch..................................................................
            } catch (SQLException ex) {
                System.out.println(ex + "Errrrrrrrrrrrrr");
                //  Logger.getLogger(Charge.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Errror in Inserting!");

            }
        }

    }//GEN-LAST:event_jButton_AddOrderActionPerformed

    private void jButton_ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearAllActionPerformed
        //6 7 4  jTextField1

        // clear ChargingRate ,,,, NoOf KM,,,, & Charge

        // jTextField4.setText("");
        jTextField_TripKM.setText("");
        jTextField_DeliveryCharge.setText("");
        jTextField_HandOverDate.setText("");
        jTextField_CusOrderID.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ClearAllActionPerformed

    private void jTextField_HandOverDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HandOverDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HandOverDateActionPerformed

    private void jButton_SeachCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SeachCustIDActionPerformed
        // TODO add your handling code here:



//        String cusOrderID = jComboBox_CusOrID.getSelectedItem().toString();
        String agentId = jComboBox_AgentID.getSelectedItem().toString();
        cusOrderID = Integer.parseInt(jTextField1.getText());

        //Add import for DB_Access
        try {
            ResultSet rs = dba.getData("select * from order_delivery where agentId='" + agentId + "'AND cusOrderID='" + cusOrderID + "'");
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int row = dtm.getRowCount();
            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }
            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                dtm.addRow(ob);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "SQL Error", "Error", 0);
        }

    }//GEN-LAST:event_jButton_SeachCustIDActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        int row = jTable2.getSelectedRow();

        if (jTable2.getRowSelectionAllowed()) {

            jTextField_CusOrderID.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
            jTextField1.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());


           
            jComboBox4.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
            jComboBox_AgentID.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());


            jTextField_TripKM.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
            jTextField_DeliveryCharge.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
            jTextField_HandOverDate.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        }

        jTextField_CusOrderID.setEnabled(false);
        jTextField_AgentID.setEnabled(false);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton_CalculateChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalculateChargeActionPerformed



        if (jTextField_TripKM.getText().isEmpty() || jTextField_ChargingRate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill Texts", "Error", 0);
        } else {
            this.tripKM = Integer.parseInt(jTextField_TripKM.getText());
            this.chargingRate = Float.parseFloat(jTextField_ChargingRate.getText());

            //CALCULATE CHARDE USING KM & CHARGINGRATE************

            //1st we caste charging rate into double then it multiply by NOOFKM*************

            this.deliveryCost = tripKM * (double) chargingRate;

            //BOZ WE CNT CONVENT TO STRING DIRECTLY**********
            //SO WE USE THIS FUNCTION

            //also we need only use 2 double values for RS:  (50.00)

            BigDecimal bd = new BigDecimal(this.deliveryCost);
            bd = bd.setScale(2, BigDecimal.ROUND_HALF_EVEN);

            jTextField_DeliveryCharge.setText(bd.toString());

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CalculateChargeActionPerformed

    }
    private void jTextField_DeliveryChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DeliveryChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DeliveryChargeActionPerformed

    private void jTextField_TripKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TripKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TripKMActionPerformed

    private void jButton_Demo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo3ActionPerformed
        // TODO add your handling code here:

        jTextField_CusOrderID.setText("3");
        jTextField_HandOverDate.setText("2022-07-28");
        jTextField_TripKM.setText("25");
        jTextField_ChargingRate.setText("100");

    }//GEN-LAST:event_jButton_Demo3ActionPerformed

    private void jButton_Demo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo1ActionPerformed
        // TODO add your handling code here:

        jTextField_AgentID.setText("900");
        jTextField_AgentName.setText("Sameera");
        jTextField_Company.setText("Aramex");
        jTextField_Phone.setText("0785214700");
        jTextField_Location.setText("Malabe");
        jTextField_ChargingRate.setText("200");

        //  jTextField6.setText("25");
    }//GEN-LAST:event_jButton_Demo1ActionPerformed

    private void jTable2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2FocusGained

    private void jTextField_AgentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_AgentIDFocusLost
        // TODO add your handling code here:




        Validator v = new Validator();
        result = v.isNumber(jTextField_AgentID.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid AgentID!");
        }

    }//GEN-LAST:event_jTextField_AgentIDFocusLost

    private void jTextField_AgentNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_AgentNameFocusLost
        // TODO add your handling code here:

        Validator v = new Validator();
        result = v.isText(jTextField_AgentName.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Agent Name!");
        }





    }//GEN-LAST:event_jTextField_AgentNameFocusLost

    private void jTextField_PhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PhoneFocusLost
        // TODO add your handling code here:




        Validator v = new Validator();
        result = v.isNumber(jTextField_Phone.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number!");
        }

    }//GEN-LAST:event_jTextField_PhoneFocusLost

    private void jTextField_CompanyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CompanyFocusLost
        // TODO add your handling code here:
        Validator v = new Validator();
        result = v.isText(jTextField_Company.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Company Name!");
        }
    }//GEN-LAST:event_jTextField_CompanyFocusLost

    private void jTextField_LocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LocationFocusLost
        // TODO add your handling code here:
        Validator v = new Validator();
        result = v.isText(jTextField_Location.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Location!");

        }
    }//GEN-LAST:event_jTextField_LocationFocusLost

    private void jTextField_TripKMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TripKMFocusLost
        // TODO add your handling code here:

        Validator v = new Validator();
        result = v.isNumber(jTextField_TripKM.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Trip Km!");
        }
    }//GEN-LAST:event_jTextField_TripKMFocusLost

    private void jButton_ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewAllActionPerformed
        // TODO add your handling code here:

        try {
            ResultSet rs = dba.getData("select * from delivery_agent");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int row = dtm.getRowCount();
            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }
            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                dtm.addRow(ob);
            }
        } catch (Exception e) {
            
             System.out.println(e + "Errrrrrrrrrrrr");
            JOptionPane.showMessageDialog(this, "SQL Error", "Error", 0);
        }
    }//GEN-LAST:event_jButton_ViewAllActionPerformed

    private void jButton_ViewAllOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewAllOrActionPerformed
        // TODO add your handling code here:

        try {
            ResultSet rs = dba.getData("select * from order_delivery");
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int row = dtm.getRowCount();
            for (int i = 0; i < row; i++) {
                dtm.removeRow(0);
            }
            while (rs.next()) {
                Object ob[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                dtm.addRow(ob);
            }
        } catch (Exception e) {
            
            System.out.println(e + "Errrrrrrrrrrrr");
            JOptionPane.showMessageDialog(this, "SQL Error", "Error", 0);
        }

    }//GEN-LAST:event_jButton_ViewAllOrActionPerformed

    private void jTextField_ChargingRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ChargingRateFocusLost
        // TODO add your handling code here:
        Validator v = new Validator();
        result = v.isNumber(jTextField_ChargingRate.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Charging Rate!");
        }


    }//GEN-LAST:event_jTextField_ChargingRateFocusLost

    private void jComboBox_ArgentID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ArgentID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ArgentID1ActionPerformed

    private void jButton_ViewReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewReportsActionPerformed
        // TODO add your handling code here:


        IReports IR = new IReports();
        IR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ViewReportsActionPerformed

    private void jButton_RefreshCourierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshCourierActionPerformed
        // TODO add your handling code here:

        jComboBox_ArgentID1.removeAllItems();
        filAgentId();

    }//GEN-LAST:event_jButton_RefreshCourierActionPerformed

    private void jButton_RefreshOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshOrderActionPerformed
        // TODO add your handling code here:'

        
        jComboBox_AgentID.removeAllItems();
        filAgentId2();
      

    }//GEN-LAST:event_jButton_RefreshOrderActionPerformed

    private void jComboBox_AgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AgentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AgentIDActionPerformed

    private void jTextField_CusOrderIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CusOrderIDFocusLost
        // TODO add your handling code here:

        Validator v = new Validator();
        result = v.isNumber(jTextField_CusOrderID.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid CusOrder_ID!");
        }
    }//GEN-LAST:event_jTextField_CusOrderIDFocusLost

    private void jTextField_CusOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CusOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CusOrderIDActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed

    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_home1ActionPerformed
 this.dispose();
        //new Charge().setVisible(true);
        new Home().setVisible(true);
        
    }//GEN-LAST:event_jButton_home1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Charge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Charge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Charge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Charge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Charge().setVisible(true);
            }
        });
    }

    public ArrayList getAgentId() {

        ArrayList AgentIdList = null;
        Connection dbConn = null;

        try {

            dbConn = dbm.connect();

            Statement stmt = dbConn.createStatement();

            String query = "SELECT DISTINCT agentId  FROM delivery_agent";

            System.out.println(query);
            ResultSet rs = stmt.executeQuery(query);

            AgentIdList = new ArrayList();

            while (rs.next()) {
                String A_ID = rs.getString(1);
                System.out.println(A_ID);
                AgentIdList.add(A_ID);
            }

        } catch (SQLException sQLException) {
            System.out.println(sQLException + "-----------Select query failed at JobCatNames");
        } finally {

            //dbm.con_Close(dbConn);
        }
        return AgentIdList;
    }

    private void filAgentId() {
        ArrayList AgentIdList = getAgentId();
        Iterator i = AgentIdList.iterator();

        while (i.hasNext()) {
            jComboBox_ArgentID1.addItem(i.next());
        }
        String AgentID = jComboBox_ArgentID1.getSelectedItem().toString();

    }

    //Find Cust_ID-----------------------------------------------------------
    
  

    //Cust_Order AgentId---------------------------------------------
   
    private void filAgentId2() {
        ArrayList AgentIdList = getAgentId();
        Iterator i = AgentIdList.iterator();

        while (i.hasNext()) {
            jComboBox_AgentID.addItem(i.next());
        }
        String AgentID = jComboBox_AgentID.getSelectedItem().toString();

    }

  public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }

    private void filAgentId3() {
        ArrayList AgentIdList = getAgentId();
        Iterator i = AgentIdList.iterator();

        while (i.hasNext()) {
            jComboBox4.addItem(i.next());
        }
        String AgentID = jComboBox4.getSelectedItem().toString();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton_AddAgent;
    private javax.swing.JButton jButton_AddOrder;
    private javax.swing.JButton jButton_CalculateCharge;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_ClearAll;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_DeleteOrd;
    private javax.swing.JButton jButton_Demo1;
    private javax.swing.JButton jButton_Demo3;
    private javax.swing.JButton jButton_FindBestCourier;
    private javax.swing.JButton jButton_RefreshCourier;
    private javax.swing.JButton jButton_RefreshOrder;
    private javax.swing.JButton jButton_SeachCustID;
    private javax.swing.JButton jButton_SearchAgntID;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JButton jButton_UpdateOrd;
    private javax.swing.JButton jButton_ViewAll;
    private javax.swing.JButton jButton_ViewAllOr;
    private javax.swing.JButton jButton_ViewReports;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_home1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox_AgentID;
    private javax.swing.JComboBox jComboBox_ArgentID1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_AgentID;
    private javax.swing.JTextField jTextField_AgentName;
    private javax.swing.JTextField jTextField_ChargingRate;
    private javax.swing.JTextField jTextField_Company;
    private javax.swing.JTextField jTextField_CusOrderID;
    private javax.swing.JTextField jTextField_DeliveryCharge;
    private javax.swing.JTextField jTextField_HandOverDate;
    private javax.swing.JTextField jTextField_Location;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_TripKM;
    // End of variables declaration//GEN-END:variables
}
