/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.Validator;
import Data.SuppliedOrder;
import Data.Supplier;
import gui.DatePicker;
import gui.EmpMng.Home;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oshani
 */
public class importing extends javax.swing.JFrame {

    boolean supplier;
    String supName;
    String supCompany;
    int supPhone;
    String supAddress;
    String supEmail;
    int orderID = 0;
    String orderdDate;
    double orderPrice;
    boolean result;
    int noCount = 0;

    /**
     * Creates new form importing
     */
    public importing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_SupPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_SupName = new javax.swing.JTextField();
        jTextField_SupCompany = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_SupAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_SupEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SupOrder = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField_SearchSname = new javax.swing.JTextField();
        jButton1_date = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_SOdrDate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_OSName = new javax.swing.JTextField();
        jTextField_OSPhone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jButton_ViewSup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Supplier = new javax.swing.JTable();
        jTextField_SearchOID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton_AddOModels = new javax.swing.JButton();
        jButton_AddOS = new javax.swing.JButton();
        jButton_UpdateOS = new javax.swing.JButton();
        jButton_RemoveOS = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton_ClearOS = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton_ShipMng = new javax.swing.JButton();
        jButton_ViewOrder = new javax.swing.JButton();
        jButton_CalcOCost = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_Demo2 = new javax.swing.JButton();
        jButton_Demo1 = new javax.swing.JButton();
        jLabel_Date = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField_OPrice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton_order = new javax.swing.JRadioButton();
        jRadioButton_supplier = new javax.swing.JRadioButton();
        jButton_Demo3 = new javax.swing.JButton();
        jButton_Demo4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton_Demo6 = new javax.swing.JButton();
        jButton_Demo5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField_Rate = new javax.swing.JTextField();
        jTextField_USprice = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton_CalcPrice = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1140, 550, 150, 50);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home);
        jButton_home.setBounds(1220, 630, 50, 35);

        jButton_back.setBackground(new java.awt.Color(0, 153, 204));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(1160, 630, 50, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1280, 150);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 160);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Supplier Details");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 250, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("+86");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 320, 30, 15);

        jTextField_SupPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SupPhoneActionPerformed(evt);
            }
        });
        jTextField_SupPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SupPhoneFocusLost(evt);
            }
        });
        jTextField_SupPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SupPhoneKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_SupPhone);
        jTextField_SupPhone.setBounds(170, 310, 220, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Select one Option :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 190, 120, 15);

        jTextField_SupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SupNameActionPerformed(evt);
            }
        });
        jTextField_SupName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SupNameKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_SupName);
        jTextField_SupName.setBounds(170, 260, 220, 30);

        jTextField_SupCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SupCompanyActionPerformed(evt);
            }
        });
        jTextField_SupCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SupCompanyKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_SupCompany);
        jTextField_SupCompany.setBounds(170, 360, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Company : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 370, 90, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 420, 110, 15);

        jTextField_SupAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SupAddressActionPerformed(evt);
            }
        });
        jTextField_SupAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SupAddressFocusLost(evt);
            }
        });
        jTextField_SupAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SupAddressKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_SupAddress);
        jTextField_SupAddress.setBounds(170, 410, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Ex: name123@gmail.com");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 490, 150, 15);

        jTextField_SupEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SupEmailActionPerformed(evt);
            }
        });
        jTextField_SupEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SupEmailFocusLost(evt);
            }
        });
        jTextField_SupEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SupEmailKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_SupEmail);
        jTextField_SupEmail.setBounds(170, 460, 220, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Supplied Orders Management");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 180, 250, 17);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(130, 230, 260, 10);

        jTable_SupOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Ordered Date", "Price", "Supplier Name", "Phone No"
            }
        ));
        jTable_SupOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SupOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_SupOrder);
        if (jTable_SupOrder.getColumnModel().getColumnCount() > 0) {
            jTable_SupOrder.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 570, 570, 100);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Supplier Name :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 540, 90, 15);

        jTextField_SearchSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchSnameActionPerformed(evt);
            }
        });
        jTextField_SearchSname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SearchSnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchSnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_SearchSname);
        jTextField_SearchSname.setBounds(170, 530, 140, 30);

        jButton1_date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1_date.setText("Select");
        jButton1_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_dateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_date);
        jButton1_date.setBounds(1020, 260, 70, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("E-mail : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 470, 110, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Ordered Date : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(680, 270, 90, 15);

        jTextField_SOdrDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SOdrDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_SOdrDate);
        jTextField_SOdrDate.setBounds(780, 260, 220, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Supplier Name : ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(680, 310, 110, 15);

        jTextField_OSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OSNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_OSName);
        jTextField_OSName.setBounds(780, 300, 220, 30);

        jTextField_OSPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OSPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_OSPhone);
        jTextField_OSPhone.setBounds(780, 340, 220, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Phone Number : ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(680, 350, 110, 15);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(770, 230, 270, 10);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Order Details");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(660, 220, 250, 17);

        jButton_ViewSup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ViewSup.setText("View All");
        jButton_ViewSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewSupActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ViewSup);
        jButton_ViewSup.setBounds(410, 530, 80, 30);

        jTable_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Company", "Phone No", "Address", "Email"
            }
        ));
        jTable_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Supplier);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 570, 550, 100);

        jTextField_SearchOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchOIDActionPerformed(evt);
            }
        });
        jTextField_SearchOID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SearchOIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchOIDKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_SearchOID);
        jTextField_SearchOID.setBounds(790, 530, 180, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Order Id :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(680, 540, 80, 15);

        jButton_AddOModels.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AddOModels.setText("Add Product Models");
        jButton_AddOModels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOModelsActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AddOModels);
        jButton_AddOModels.setBounds(1140, 250, 150, 50);

        jButton_AddOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AddOS.setText("Insert ");
        jButton_AddOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AddOS);
        jButton_AddOS.setBounds(520, 290, 80, 30);

        jButton_UpdateOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_UpdateOS.setText("Update");
        jButton_UpdateOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_UpdateOS);
        jButton_UpdateOS.setBounds(520, 340, 80, 30);

        jButton_RemoveOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_RemoveOS.setText("Remove");
        jButton_RemoveOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RemoveOS);
        jButton_RemoveOS.setBounds(520, 390, 77, 30);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 1300, 160);

        jButton_ClearOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ClearOS.setText("Clear");
        jButton_ClearOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ClearOS);
        jButton_ClearOS.setBounds(520, 440, 80, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Management");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1180, 380, 72, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Shipping");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1190, 360, 50, 14);

        jButton_ShipMng.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ShipMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShipMngActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ShipMng);
        jButton_ShipMng.setBounds(1140, 350, 150, 50);

        jButton_ViewOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ViewOrder.setText("View All");
        jButton_ViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ViewOrder);
        jButton_ViewOrder.setBounds(1020, 530, 80, 30);

        jButton_CalcOCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CalcOCost.setText("Calculate Order Cost");
        jButton_CalcOCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcOCostActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CalcOCost);
        jButton_CalcOCost.setBounds(1140, 450, 150, 50);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1130, 160, 170, 540);

        jButton_Demo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo2.setText("Demo1");
        jButton_Demo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo2);
        jButton_Demo2.setBounds(1020, 300, 71, 30);

        jButton_Demo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo1.setText("Demo1");
        jButton_Demo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo1);
        jButton_Demo1.setBounds(410, 260, 71, 30);
        getContentPane().add(jLabel_Date);
        jLabel_Date.setBounds(970, 170, 150, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Ceylon Price : ");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(680, 470, 110, 15);

        jTextField_OPrice.setRequestFocusEnabled(false);
        jTextField_OPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OPriceActionPerformed(evt);
            }
        });
        jTextField_OPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_OPriceKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_OPrice);
        jTextField_OPrice.setBounds(820, 460, 180, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Rs.");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(780, 470, 30, 20);

        jRadioButton_order.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_order.setText("Order");
        jRadioButton_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_orderActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_order);
        jRadioButton_order.setBounds(530, 210, 93, 23);

        jRadioButton_supplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_supplier.setSelected(true);
        jRadioButton_supplier.setText("Supplier");
        jRadioButton_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_supplier);
        jRadioButton_supplier.setBounds(430, 210, 71, 23);

        jButton_Demo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo3.setText("Demo2");
        jButton_Demo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo3);
        jButton_Demo3.setBounds(410, 310, 71, 30);

        jButton_Demo4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo4.setText("Demo3");
        jButton_Demo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo4);
        jButton_Demo4.setBounds(410, 360, 71, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Phone Number : ");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(40, 320, 110, 15);

        jButton_Demo6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo6.setText("Demo2");
        jButton_Demo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo6);
        jButton_Demo6.setBounds(1020, 340, 71, 30);

        jButton_Demo5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Demo5.setText("Demo3");
        jButton_Demo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Demo5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Demo5);
        jButton_Demo5.setBounds(1020, 380, 71, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Supplier Name : ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(40, 270, 90, 15);

        jTextField_Rate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_RateFocusLost(evt);
            }
        });
        getContentPane().add(jTextField_Rate);
        jTextField_Rate.setBounds(820, 420, 180, 30);

        jTextField_USprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_USpriceActionPerformed(evt);
            }
        });
        jTextField_USprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_USpriceKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_USprice);
        jTextField_USprice.setBounds(820, 380, 180, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Order Price : ");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(680, 390, 110, 15);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("USD Rate : ");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(680, 430, 110, 15);

        jButton_CalcPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CalcPrice.setText("Calculate");
        jButton_CalcPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcPriceActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CalcPrice);
        jButton_CalcPrice.setBounds(1020, 420, 90, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("USD.");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(780, 390, 30, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Rs.");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(780, 430, 30, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Refersh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 490, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_SupPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SupPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SupPhoneActionPerformed

    private void jTextField_SupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SupNameActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Invalid Email");
    }//GEN-LAST:event_jTextField_SupNameActionPerformed

    private void jTextField_SupCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SupCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SupCompanyActionPerformed

    private void jTextField_SupAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SupAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SupAddressActionPerformed

    private void jTextField_SupEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SupEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SupEmailActionPerformed

    private void jTextField_SearchSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchSnameActionPerformed

    private void jButton1_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_dateActionPerformed
        // TODO add your handling code here:
        DatePicker dp = new gui.DatePicker(this);
        jTextField_SOdrDate.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton1_dateActionPerformed

    private void jTextField_SOdrDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SOdrDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SOdrDateActionPerformed

    private void jTextField_OSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OSNameActionPerformed

    private void jTextField_OSPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OSPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OSPhoneActionPerformed

    private void jButton_ViewSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewSupActionPerformed
        // TODO add your handling code here:
        Supplier sup = new Supplier();
        ResultSet rst = sup.getSupplierDetails();

        showTable(rst, true);
    }//GEN-LAST:event_jButton_ViewSupActionPerformed

    private void jButton_ShipMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShipMngActionPerformed
        // TODO add your handling code here:
        Shipping sp = new Shipping();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton_ShipMngActionPerformed

    private void jTextField_SearchOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchOIDActionPerformed

    private void jButton_AddOModelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOModelsActionPerformed
        // TODO add your handling code here:
        try {

            int row = jTable_SupOrder.getSelectedRow();
            orderID = Integer.parseInt(jTable_SupOrder.getValueAt(row, 0).toString());
            displayModelPage();
        } catch (ArrayIndexOutOfBoundsException ex) {

            try {
                orderID = Integer.parseInt(jTable_SupOrder.getValueAt(0, 0).toString());
                displayModelPage();
            } catch (NullPointerException ex2) {

                JOptionPane.showMessageDialog(this, "Please select an Order ID from the table!");
            }

        }

    }//GEN-LAST:event_jButton_AddOModelsActionPerformed

    private void jButton_AddOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddOSActionPerformed
        // TODO add your handling code here:
        if (supplier) {
            if (jTextField_SupName.getText().isEmpty() || jTextField_SupPhone.getText().isEmpty() || jTextField_SupEmail.getText().isEmpty()
                    || jTextField_SupAddress.getText().isEmpty() || jTextField_SupCompany.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");
            } else {
                supName = jTextField_SupName.getText();
                supCompany = jTextField_SupCompany.getText();
                supPhone = Integer.parseInt(jTextField_SupPhone.getText());
                supAddress = jTextField_SupAddress.getText();
                supEmail = jTextField_SupEmail.getText();

                Supplier sup = new Supplier(supName, supCompany, supPhone, supAddress, supEmail);
                result = sup.addSuppliers();

                if (result) {
                    JOptionPane.showMessageDialog(this, "Insertion is Successful!");
                } else {
                    JOptionPane.showMessageDialog(this, "Insertion is not Successful!");
                }

                ResultSet rst = sup.SearchSuppliers(supName);
                showTable(rst, true);
            }

        } else if (!supplier) {

            if (jTextField_OPrice.getText().isEmpty() || jTextField_OSName.getText().isEmpty() || jTextField_OSPhone.getText().isEmpty()
                    || jTextField_SOdrDate.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");
            } else {

                orderdDate = jTextField_SOdrDate.getText();
                supName = jTextField_OSName.getText();
                supPhone = Integer.parseInt(jTextField_OSPhone.getText());
                orderPrice = Double.parseDouble(jTextField_OPrice.getText());


                SuppliedOrder so = new SuppliedOrder(orderdDate, supName, supPhone, orderPrice);
                result = so.addSupplliedOrders();

                if (result) {
                    JOptionPane.showMessageDialog(this, "Insertion is Successful!");
                } else {
                    JOptionPane.showMessageDialog(this, "Insertion is not Successful!");
                }

                orderID = so.getOrderID(orderdDate, supName);
                ResultSet rst = so.SearchOrders(orderID);
                showTable(rst, false);

            }

        }

    }//GEN-LAST:event_jButton_AddOSActionPerformed

    private void jButton_UpdateOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateOSActionPerformed
        // TODO add your handling code here:

        ResultSet rst;

        if (supplier) {

            if (jTextField_SupName.getText().isEmpty() || jTextField_SupPhone.getText().isEmpty() || jTextField_SupEmail.getText().isEmpty()
                    || jTextField_SupAddress.getText().isEmpty() || jTextField_SupCompany.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");
            } else {
                supName = jTextField_SupName.getText();
                supCompany = jTextField_SupCompany.getText();
                supPhone = Integer.parseInt(jTextField_SupPhone.getText());
                supAddress = jTextField_SupAddress.getText();
                supEmail = jTextField_SupEmail.getText();

                Supplier sup = new Supplier(supName, supCompany, supPhone, supAddress, supEmail);
                result = sup.updateSuppliers();

                if (result) {
                    JOptionPane.showMessageDialog(this, "Updating is Successful!");
                } else {
                    JOptionPane.showMessageDialog(this, "Updating is not Successful!");
                }

                rst = sup.SearchSuppliers(supName);
                showTable(rst, true);

                jTextField_SupName.setEnabled(true);
                jTextField_SupPhone.setEnabled(true);
            }
        } else if (!supplier) {

            if (jTextField_OPrice.getText().isEmpty() || jTextField_OSName.getText().isEmpty() || jTextField_OSPhone.getText().isEmpty()
                    || jTextField_SOdrDate.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");
            } else {
                int row = jTable_SupOrder.getSelectedRow();

                if (jTable_Supplier.getRowSelectionAllowed()) {
                    orderID = Integer.parseInt(jTable_SupOrder.getValueAt(row, 0).toString());
                }

                orderdDate = jTextField_SOdrDate.getText();
                orderPrice = Double.parseDouble(jTextField_OPrice.getText());
                supName = jTextField_OSName.getText();
                supPhone = Integer.parseInt(jTextField_OSPhone.getText());

                SuppliedOrder so = new SuppliedOrder(orderdDate, supName, supPhone, orderPrice);
                result = so.updateOrder(orderID);

                if (result) {
                    JOptionPane.showMessageDialog(this, "Updating is Successful!");
                } else {
                    JOptionPane.showMessageDialog(this, "Updating is not Successful!");
                }

                rst = so.SearchOrders(orderID);
                showTable(rst, false);
            }
        }


    }//GEN-LAST:event_jButton_UpdateOSActionPerformed

    private void jButton_RemoveOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveOSActionPerformed
        // TODO add your handling code here:
        if (supplier) {
            supName = jTable_Supplier.getValueAt(0, 0).toString();
            Supplier sp = new Supplier();
            result = sp.removeSupplier(supName);

            if (result) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted!");
            } else {
                JOptionPane.showMessageDialog(this, "Deleting is not Successful!");
            }

            ResultSet rst = sp.getSupplierDetails();
            showTable(rst, true);
        } else if (!supplier) {

            orderID = Integer.parseInt(jTextField_SearchOID.getText());
            SuppliedOrder so = new SuppliedOrder();
            result = so.removeOrder(orderID);

            if (result) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted!");
            } else {
                JOptionPane.showMessageDialog(this, "Deleting is not Successful!");
            }

            ResultSet rst = so.getOrders();
            showTable(rst, false);
        }

    }//GEN-LAST:event_jButton_RemoveOSActionPerformed

    private void jButton_ClearOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearOSActionPerformed
        // TODO add your handling code here:

        setClear();

    }//GEN-LAST:event_jButton_ClearOSActionPerformed

    private void jButton_ViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewOrderActionPerformed
        // TODO add your handling code here:
        SuppliedOrder so = new SuppliedOrder();
        ResultSet rst = so.getOrders();
        showTable(rst, false);
    }//GEN-LAST:event_jButton_ViewOrderActionPerformed

    private void jButton_CalcOCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcOCostActionPerformed
        // TODO add your handling code here:
        OrderPrice op = new OrderPrice();
        op.setVisible(true);
    }//GEN-LAST:event_jButton_CalcOCostActionPerformed

    private void jTable_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SupplierMouseClicked
        // TODO add your handling code here:
        if (supplier) {
            int row = jTable_Supplier.getSelectedRow();

            if (jTable_Supplier.getRowSelectionAllowed()) {

                jTextField_SupName.setText(jTable_Supplier.getValueAt(row, 0).toString());
                jTextField_SupPhone.setText(jTable_Supplier.getValueAt(row, 2).toString());
                jTextField_SupCompany.setText(jTable_Supplier.getValueAt(row, 1).toString());
                jTextField_SupAddress.setText(jTable_Supplier.getValueAt(row, 3).toString());
                jTextField_SupEmail.setText(jTable_Supplier.getValueAt(row, 4).toString());
            }

            jTextField_SupName.setEnabled(false);
            jTextField_SupPhone.setEnabled(false);
        } else if (!supplier) {

            int row = jTable_Supplier.getSelectedRow();

            if (jTable_Supplier.getRowSelectionAllowed()) {

                jTextField_OSName.setText(jTable_Supplier.getValueAt(row, 0).toString());
                jTextField_OSPhone.setText(jTable_Supplier.getValueAt(row, 2).toString());
            }

        }
    }//GEN-LAST:event_jTable_SupplierMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        setVisibility(true);

    }//GEN-LAST:event_formWindowOpened

    private void jButton_Demo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo1ActionPerformed
        // TODO add your handling code here:
        jTextField_SupName.setText("Tomoko Naraoka");
        jTextField_SupCompany.setText("Yukiko Okamoto");
        jTextField_SupPhone.setText("581365836");
        jTextField_SupAddress.setText("Biejing, Chaina");
        jTextField_SupEmail.setText("tomokotest@gmail.com");


    }//GEN-LAST:event_jButton_Demo1ActionPerformed

    private void jTextField_OPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OPriceActionPerformed

    private void jRadioButton_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_orderActionPerformed
        // TODO add your handling code here:

        setVisibility(false);

    }//GEN-LAST:event_jRadioButton_orderActionPerformed

    private void jRadioButton_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_supplierActionPerformed
        // TODO add your handling code here:

        setVisibility(true);

    }//GEN-LAST:event_jRadioButton_supplierActionPerformed

    private void jButton_Demo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo2ActionPerformed
        // TODO add your handling code here:

        jTextField_OPrice.setText("50000");

    }//GEN-LAST:event_jButton_Demo2ActionPerformed

    private void jTable_SupOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SupOrderMouseClicked
        // TODO add your handling code here:
        int row = jTable_SupOrder.getSelectedRow();

        if (jTable_SupOrder.getRowSelectionAllowed()) {

            jTextField_SOdrDate.setText(jTable_SupOrder.getValueAt(row, 1).toString());
            jTextField_OPrice.setText(jTable_SupOrder.getValueAt(row, 2).toString());
            jTextField_OSName.setText(jTable_SupOrder.getValueAt(row, 3).toString());
            jTextField_OSPhone.setText(jTable_SupOrder.getValueAt(row, 4).toString());
        }

    }//GEN-LAST:event_jTable_SupOrderMouseClicked

    private void jButton_Demo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo3ActionPerformed
        // TODO add your handling code here:

        jTextField_SupName.setText("Yuko Tanaka");
        jTextField_SupCompany.setText("Yuko");
        jTextField_SupPhone.setText("544445836");
        jTextField_SupAddress.setText("Honkong, Chaina");
        jTextField_SupEmail.setText("yukotest@gmail.com");

    }//GEN-LAST:event_jButton_Demo3ActionPerformed

    private void jButton_Demo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo4ActionPerformed
        // TODO add your handling code here:
        jTextField_SearchSname.setText("Emma Fang");
    }//GEN-LAST:event_jButton_Demo4ActionPerformed

    private void jButton_Demo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo5ActionPerformed
        // TODO add your handling code here:
        jTextField_SearchOID.setText("28");
    }//GEN-LAST:event_jButton_Demo5ActionPerformed

    private void jButton_Demo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Demo6ActionPerformed
        // TODO add your handling code here:
        jTextField_OPrice.setText("50000");
    }//GEN-LAST:event_jButton_Demo6ActionPerformed

    private void jTextField_SupPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SupPhoneFocusLost
        // TODO add your handling code here:

        if ((jTextField_SupPhone.getText().length() != 9) && (!jTextField_SupPhone.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number!\nNumber should contains only 9 digits");
        }

    }//GEN-LAST:event_jTextField_SupPhoneFocusLost

    private void jTextField_SupAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SupAddressFocusLost
        // TODO add your handling code here:
        Validator v = new Validator();
        result = v.isAddress(jTextField_SupAddress.getText());

        if (!result) {
            JOptionPane.showMessageDialog(this, "Invalid Address!");
        }
    }//GEN-LAST:event_jTextField_SupAddressFocusLost

    private void jTextField_SupEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SupEmailFocusLost
        // TODO add your handling code here:
        if (!jTextField_SupEmail.getText().isEmpty()) {
            Validator v = new Validator();
            result = v.checkEmail(jTextField_SupEmail.getText());

            if (!result) {
                JOptionPane.showMessageDialog(this, "Invalid Email!");
            }
        }

    }//GEN-LAST:event_jTextField_SupEmailFocusLost

    private void jTextField_SearchOIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchOIDKeyReleased
        // TODO add your handling code here:

        if (!jTextField_SearchOID.getText().isEmpty()) {

            orderID = Integer.parseInt(jTextField_SearchOID.getText());

            SuppliedOrder so = new SuppliedOrder();
            ResultSet rst = so.SearchOrders(orderID);


            if (rst == null) {

                JOptionPane.showMessageDialog(this, "Searching Details are not exist!!!");
            } else {

                showTable(rst, false);
            }

        }

    }//GEN-LAST:event_jTextField_SearchOIDKeyReleased

    private void jTextField_SearchSnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchSnameKeyPressed
        // TODO add your handling code here:
        jTextField_SearchSname.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar() == '.') && !(Character.isWhitespace(e.getKeyChar()))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SearchSnameKeyPressed

    private void jTextField_SearchOIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchOIDKeyPressed
        // TODO add your handling code here:
        jTextField_SearchOID.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar())) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SearchOIDKeyPressed

    private void jTextField_SearchSnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchSnameKeyReleased
        // TODO add your handling code here:
        if (!jTextField_SearchSname.getText().isEmpty() && !jTextField_SearchSname.getText().equals(" ")) {

            ResultSet rst;
            supName = jTextField_SearchSname.getText();
            Supplier sup = new Supplier();


            if (!sup.checkSupplierName(supName)) {

                JOptionPane.showMessageDialog(this, "Search key is not exist!");
            } else {

                rst = sup.SearchSuppliers(supName);
                showTable(rst, true);
            }
        }
    }//GEN-LAST:event_jTextField_SearchSnameKeyReleased

    private void jTextField_SupNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupNameKeyPressed
        // TODO add your handling code here:
        jTextField_SupName.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar() == '.') && !(Character.isWhitespace(e.getKeyChar()))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SupNameKeyPressed

    private void jTextField_SupPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupPhoneKeyPressed
        // TODO add your handling code here:
        jTextField_SupPhone.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar())) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SupPhoneKeyPressed

    private void jTextField_SupCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupCompanyKeyPressed
        // TODO add your handling code here:
        jTextField_SupCompany.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar() == '.') && !(Character.isWhitespace(e.getKeyChar()))
                        && !(e.getKeyChar() == '(') && !(e.getKeyChar() == ')')) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SupCompanyKeyPressed

    private void jTextField_SupAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupAddressKeyPressed
        // TODO add your handling code here:
        jTextField_SupAddress.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar() == '.') && !(Character.isWhitespace(e.getKeyChar()))
                        && !(e.getKeyChar() == '(') && !(e.getKeyChar() == ')') && !(e.getKeyChar() == '/') && !(e.getKeyChar() == '-')
                        && !(e.getKeyChar() == ',') && !(Character.isDigit(e.getKeyChar()))) {
                    e.consume();
                }
            }
        });

    }//GEN-LAST:event_jTextField_SupAddressKeyPressed

    private void jTextField_SupEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupEmailKeyPressed
        // TODO add your handling code here:
        jTextField_SupEmail.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar() == '.') && !(Character.isDigit(e.getKeyChar()))
                        && !(e.getKeyChar() == '@')) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_SupEmailKeyPressed

    private void jTextField_OPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_OPriceKeyPressed
        // TODO add your handling code here:
        jTextField_OPrice.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar()) && !(e.getKeyChar() == '.')) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_jTextField_OPriceKeyPressed

    private void jTextField_USpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_USpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_USpriceActionPerformed

    private void jTextField_USpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_USpriceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_USpriceKeyPressed

    private void jButton_CalcPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcPriceActionPerformed
        // TODO add your handling code here:

        if (jTextField_Rate.getText().isEmpty() || jTextField_USprice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill US Price & USD rate!");
        } else {
            double usPrice = Double.parseDouble(jTextField_USprice.getText());
            double rate = Double.parseDouble(jTextField_Rate.getText());

           double orderPrice =  (usPrice * rate);

            //System.out.printf("dorderPrice: %f\n", orderPrice);
             jTextField_OPrice.setText(String.valueOf(orderPrice) );


        }

    }//GEN-LAST:event_jButton_CalcPriceActionPerformed

    private void jTextField_RateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_RateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RateFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        setClear();
        DefaultTableModel dtm = (DefaultTableModel) jTable_Supplier.getModel();
        int row = dtm.getRowCount();

        for (int i = 0; i < row; i++) {

            dtm.removeRow(0);
        }


        dtm = (DefaultTableModel) jTable_SupOrder.getModel();
        row = dtm.getRowCount();

        for (int i = 0; i < row; i++) {

            dtm.removeRow(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        new MonthlyReport().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

        this.dispose();
        new importing().setVisible(true);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void showTable(ResultSet rst, boolean supplier) {

        if (supplier) {
            DefaultTableModel dtm = (DefaultTableModel) jTable_Supplier.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {

                dtm.removeRow(0);
            }

            try {

                while (rst.next()) {

                    Object ob[] = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5)};
                    dtm.addRow(ob);
                }
            } catch (SQLException ex) {

                System.out.println(ex + "------------Failure of retriving data");
            }

        } else if (!supplier) {

            DefaultTableModel dtm = (DefaultTableModel) jTable_SupOrder.getModel();
            int row = dtm.getRowCount();

            for (int i = 0; i < row; i++) {

                dtm.removeRow(0);
            }

            try {

                while (rst.next()) {

                    Object ob[] = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5)};
                    dtm.addRow(ob);
                }
            } catch (SQLException ex) {

                System.out.println(ex + "------------Failure of retriving data");
            }
        }
    }

    private void displayModelPage() {

        Models mo = new Models();
        mo.getOrderID(orderID);
        mo.setVisible(true);

    }

    private void setClear() {

        jTable_SupOrder.removeAll();
        jTable_Supplier.removeAll();
        jTextField_OSName.setText(" ");
        jTextField_OSPhone.setText(" ");
        jTextField_SOdrDate.setText(" ");
        jTextField_SearchOID.setText(" ");
        jTextField_SearchSname.setText(" ");
        jTextField_SupAddress.setText(" ");
        jTextField_SupCompany.setText(" ");
        jTextField_SupEmail.setText(" ");
        jTextField_SupName.setText(" ");
        jTextField_SupPhone.setText(" ");
        jTextField_OPrice.setText(" ");
    }

    private void setVisibility(boolean isSupplier) {

        supplier = isSupplier;

        jTextField_SupPhone.setEnabled(isSupplier);
        jTextField_SupName.setEnabled(isSupplier);
        jTextField_SupEmail.setEnabled(isSupplier);
        jTextField_SupCompany.setEnabled(isSupplier);
        jTextField_SupAddress.setEnabled(isSupplier);
        jButton_Demo1.setEnabled(isSupplier);
        jButton_Demo3.setEnabled(isSupplier);
        jButton_Demo4.setEnabled(isSupplier);
        jRadioButton_supplier.setSelected(isSupplier);
        jLabel5.setEnabled(isSupplier);
        jLabel24.setEnabled(isSupplier);
        jLabel23.setEnabled(isSupplier);
        jLabel7.setEnabled(isSupplier);
        jLabel8.setEnabled(isSupplier);
        jLabel12.setEnabled(isSupplier);
        jLabel9.setEnabled(isSupplier);
        jLabel4.setEnabled(isSupplier);

        jTextField_OSName.setEnabled(false);
        jTextField_OSPhone.setEnabled(false);
        jTextField_OPrice.setEnabled(!isSupplier);
        jTextField_SOdrDate.setEnabled(!isSupplier);
        jTextField_Rate.setEnabled(!isSupplier);
        jTextField_USprice.setEnabled(!isSupplier);
        jButton_Demo2.setEnabled(!isSupplier);
        jButton1_date.setEnabled(!isSupplier);
        jButton_Demo5.setEnabled(!isSupplier);
        jButton_Demo6.setEnabled(!isSupplier);
        jRadioButton_order.setSelected(!isSupplier);
        jLabel14.setEnabled(!isSupplier);
        jLabel16.setEnabled(!isSupplier);
        jLabel17.setEnabled(!isSupplier);
        jLabel22.setEnabled(!isSupplier);
        jLabel27.setEnabled(!isSupplier);
        jLabel18.setEnabled(!isSupplier);
        jLabel25.setEnabled(!isSupplier);
        jLabel26.setEnabled(!isSupplier);
        jLabel28.setEnabled(!isSupplier);
        jLabel29.setEnabled(!isSupplier);
    }
    
    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new importing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AddOModels;
    private javax.swing.JButton jButton_AddOS;
    private javax.swing.JButton jButton_CalcOCost;
    private javax.swing.JButton jButton_CalcPrice;
    private javax.swing.JButton jButton_ClearOS;
    private javax.swing.JButton jButton_Demo1;
    private javax.swing.JButton jButton_Demo2;
    private javax.swing.JButton jButton_Demo3;
    private javax.swing.JButton jButton_Demo4;
    private javax.swing.JButton jButton_Demo5;
    private javax.swing.JButton jButton_Demo6;
    private javax.swing.JButton jButton_RemoveOS;
    private javax.swing.JButton jButton_ShipMng;
    private javax.swing.JButton jButton_UpdateOS;
    private javax.swing.JButton jButton_ViewOrder;
    private javax.swing.JButton jButton_ViewSup;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JRadioButton jRadioButton_order;
    private javax.swing.JRadioButton jRadioButton_supplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_SupOrder;
    private javax.swing.JTable jTable_Supplier;
    private javax.swing.JTextField jTextField_OPrice;
    private javax.swing.JTextField jTextField_OSName;
    private javax.swing.JTextField jTextField_OSPhone;
    private javax.swing.JTextField jTextField_Rate;
    private javax.swing.JTextField jTextField_SOdrDate;
    private javax.swing.JTextField jTextField_SearchOID;
    private javax.swing.JTextField jTextField_SearchSname;
    private javax.swing.JTextField jTextField_SupAddress;
    private javax.swing.JTextField jTextField_SupCompany;
    private javax.swing.JTextField jTextField_SupEmail;
    private javax.swing.JTextField jTextField_SupName;
    private javax.swing.JTextField jTextField_SupPhone;
    private javax.swing.JTextField jTextField_USprice;
    // End of variables declaration//GEN-END:variables
}
