/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.report;
import gui.DatePicker;
import gui.EmpMng.Home;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Oshani
 */
public class MonthlyReport extends javax.swing.JFrame {

    /**
     * Creates new form MonthlyReport
     */
    public MonthlyReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_home = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton1_date = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField_StartDate = new javax.swing.JTextField();
        jButton1_date1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField_EndDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home);
        jButton_home.setBounds(1220, 650, 50, 35);

        jButton_back.setBackground(new java.awt.Color(0, 153, 204));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(1160, 650, 50, 33);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("View Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 450, 127, 43);

        jButton1_date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1_date.setText("Select");
        jButton1_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_dateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_date);
        jButton1_date.setBounds(630, 320, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Start Date : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(290, 330, 90, 15);

        jTextField_StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_StartDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_StartDate);
        jTextField_StartDate.setBounds(390, 320, 220, 30);

        jButton1_date1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1_date1.setText("Select");
        jButton1_date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_date1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_date1);
        jButton1_date1.setBounds(630, 380, 70, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("End Date : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 390, 90, 15);

        jTextField_EndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EndDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_EndDate);
        jTextField_EndDate.setBounds(390, 380, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1280, 150);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 160);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1130, 160, 170, 540);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Monthly Imported Report");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 230, 250, 17);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(260, 240, 280, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_dateActionPerformed
        // TODO add your handling code here:
        DatePicker dp = new gui.DatePicker(this);
        jTextField_StartDate.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton1_dateActionPerformed

    private void jTextField_StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_StartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_StartDateActionPerformed

    private void jButton1_date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_date1ActionPerformed
        // TODO add your handling code here:
        DatePicker dp = new gui.DatePicker(this);
        jTextField_EndDate.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton1_date1ActionPerformed

    private void jTextField_EndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EndDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            HashMap para = new HashMap();

            para.put("paraStart", jTextField_StartDate.getText());
            para.put("paraEnd", jTextField_EndDate.getText());

//      para.put("cusID",jTextField1.getText());
            report show = new report("E:\\PROJECT\\Riyoma System\\src\\IReports\\importing.jasper", para);
            show.setVisible(true);
            
        } catch (JRException ex) {
            
            System.out.println(ex);
            
        } catch (ClassNotFoundException ex) {
            
            System.out.println(ex);
            
        } catch (SQLException ex) {
            
            System.out.println(ex);
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

        this.dispose();
        new importing().setVisible(true);

    }//GEN-LAST:event_jButton_backActionPerformed

    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyReport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_date;
    private javax.swing.JButton jButton1_date1;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField_EndDate;
    private javax.swing.JTextField jTextField_StartDate;
    // End of variables declaration//GEN-END:variables
}
