/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.ShippingDetails;
import Data.SuppliedOrder;
import gui.EmpMng.Home;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Senali
 */
public class OrderPrice extends javax.swing.JFrame {

    String shipID;
    int orderID;
    double insuranceCharges;
    double dutyCharges;
    double unloadingCharges;
    double payOrderCharges;
    double tarnsportCharges;
    double clearCharges;
    double shipingCharge;
    double orderPrice;
    double totOrderCost = 0;
    double profitMargin;
    Vector<String> headers = new Vector<String>();

    /**
     * Creates new form OrderPrice
     */
    public OrderPrice() {
        initComponents();

        fillComboBox();

        jTextField3_CShipID.setEnabled(false);
        jTextField_SOrderID.setEnabled(false);
        jTextField_OrderPrice.setEnabled(false);
        jTextField_shipCharge.setEnabled(false);

        headers.add("Model Name");
        headers.add("Bought Price(Rs.)");
        headers.add("Selling Price(Rs.)");
        headers.add("Selling Profit(Rs.)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_OrderID = new javax.swing.JComboBox();
        jButton_back = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField3_CShipID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Insurance = new javax.swing.JTextField();
        jTextField_Duty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Payorder = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Clearing = new javax.swing.JTextField();
        jButton_SearchModel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_TotCost = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTextField_SOrderID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_ProfitMrgn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ModelPrice = new javax.swing.JTable();
        jButton_CalcCost = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField_ShModeName = new javax.swing.JTextField();
        jButton_CalcSelling = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_Unloading = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_Transport = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_shipCharge = new javax.swing.JTextField();
        jTextField_OrderPrice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox_OrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OrderIDActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_OrderID);
        jComboBox_OrderID.setBounds(190, 260, 220, 30);

        jButton_back.setBackground(new java.awt.Color(0, 153, 204));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(1160, 610, 50, 33);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home);
        jButton_home.setBounds(1220, 610, 50, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1280, 150);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 160);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1130, 160, 170, 540);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Order Cost & Product Selling Price Calculation");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 180, 390, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Order Cost Calculation");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 220, 250, 17);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(190, 230, 220, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Order Id : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 270, 90, 15);

        jTextField3_CShipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_CShipIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3_CShipID);
        jTextField3_CShipID.setBounds(190, 290, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Price of Order: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 330, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Insurance :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 390, 110, 15);

        jTextField_Insurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InsuranceActionPerformed(evt);
            }
        });
        jTextField_Insurance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_InsuranceKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Insurance);
        jTextField_Insurance.setBounds(220, 380, 190, 30);

        jTextField_Duty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DutyActionPerformed(evt);
            }
        });
        jTextField_Duty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_DutyKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Duty);
        jTextField_Duty.setBounds(220, 410, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Duty & Other :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 420, 120, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Payorder Charges : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 450, 110, 15);

        jTextField_Payorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PayorderActionPerformed(evt);
            }
        });
        jTextField_Payorder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PayorderKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Payorder);
        jTextField_Payorder.setBounds(220, 440, 190, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Rs.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 480, 30, 20);

        jTextField_Clearing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ClearingActionPerformed(evt);
            }
        });
        jTextField_Clearing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ClearingKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Clearing);
        jTextField_Clearing.setBounds(220, 470, 190, 30);

        jButton_SearchModel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_SearchModel.setText("View All");
        jButton_SearchModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchModelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_SearchModel);
        jButton_SearchModel.setBounds(1020, 360, 90, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Clearing Charges : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 480, 110, 15);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setText("Total Cost");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 620, 110, 24);

        jLabel_TotCost.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_TotCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_TotCost.setText("0.00");
        getContentPane().add(jLabel_TotCost);
        jLabel_TotCost.setBounds(220, 620, 190, 24);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(500, 260, 10, 420);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Product Selling Price ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(550, 220, 250, 17);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(690, 230, 230, 10);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Order Id : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(570, 270, 90, 15);

        jTextField_SOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SOrderIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_SOrderID);
        jTextField_SOrderID.setBounds(700, 260, 220, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("%");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(790, 310, 30, 15);

        jTextField_ProfitMrgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ProfitMrgnActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ProfitMrgn);
        jTextField_ProfitMrgn.setBounds(700, 300, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Profit Margin : ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(570, 310, 90, 15);

        jTable_ModelPrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Model Name", "Buying Price(Rs.)", "Selling Price(Rs.)", "Selling Profit(Rs.)"
            }
        ));
        jScrollPane1.setViewportView(jTable_ModelPrice);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 400, 580, 260);

        jButton_CalcCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CalcCost.setText("Calculate ");
        jButton_CalcCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcCostActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CalcCost);
        jButton_CalcCost.setBounds(300, 570, 110, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Model Name : ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(570, 370, 90, 15);

        jTextField_ShModeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShModeNameActionPerformed(evt);
            }
        });
        jTextField_ShModeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ShModeNameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_ShModeName);
        jTextField_ShModeName.setBounds(700, 360, 140, 30);

        jButton_CalcSelling.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_CalcSelling.setText("Calculate ");
        jButton_CalcSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcSellingActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CalcSelling);
        jButton_CalcSelling.setBounds(860, 300, 90, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Rs.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(190, 620, 30, 24);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Rs.");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(190, 330, 30, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Rs.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(190, 420, 30, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Rs.");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(190, 450, 30, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Unloading Expenses : ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(60, 510, 120, 15);

        jTextField_Unloading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UnloadingActionPerformed(evt);
            }
        });
        jTextField_Unloading.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_UnloadingKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Unloading);
        jTextField_Unloading.setBounds(220, 500, 190, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Rs.");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(190, 510, 30, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Transport Charge : ");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(60, 540, 110, 15);

        jTextField_Transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TransportActionPerformed(evt);
            }
        });
        jTextField_Transport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_TransportKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Transport);
        jTextField_Transport.setBounds(220, 530, 190, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Rs.");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(190, 540, 30, 20);
        getContentPane().add(jTextField_shipCharge);
        jTextField_shipCharge.setBounds(220, 350, 190, 30);

        jTextField_OrderPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OrderPriceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_OrderPrice);
        jTextField_OrderPrice.setBounds(220, 320, 190, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Rs.");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(190, 360, 30, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Rs.");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(190, 390, 30, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Shipping Charges :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 360, 120, 15);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Ship Id : ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(60, 300, 90, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_CShipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_CShipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_CShipIDActionPerformed

    private void jTextField_InsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InsuranceActionPerformed

    private void jTextField_DutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DutyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DutyActionPerformed

    private void jTextField_PayorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PayorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PayorderActionPerformed

    private void jTextField_ClearingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ClearingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ClearingActionPerformed

    private void jButton_SearchModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SearchModelActionPerformed

    private void jTextField_SOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SOrderIDActionPerformed

    private void jTextField_ProfitMrgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ProfitMrgnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ProfitMrgnActionPerformed

    private void jButton_CalcCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcCostActionPerformed
        // TODO add your handling code here:
        if (jTextField_Duty.getText().isEmpty() || jTextField_Clearing.getText().isEmpty() || jTextField_Insurance.getText().isEmpty()
                || jTextField_Payorder.getText().isEmpty() || jTextField_Transport.getText().isEmpty() || jTextField_Unloading.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");
        } else {

            insuranceCharges = Double.parseDouble(jTextField_Insurance.getText().toString());
            dutyCharges = Double.parseDouble(jTextField_Duty.getText().toString());
            payOrderCharges = Double.parseDouble(jTextField_Payorder.getText().toString());
            clearCharges = Double.parseDouble(jTextField_Clearing.getText().toString());
            unloadingCharges = Double.parseDouble(jTextField_Unloading.getText().toString());
            tarnsportCharges = Double.parseDouble(jTextField_Transport.getText().toString());

            Double totCharge = insuranceCharges + dutyCharges + payOrderCharges + clearCharges + unloadingCharges + tarnsportCharges;

            ShippingDetails sp = new ShippingDetails();
            sp.addOtherCharges(totCharge, orderID);

            totOrderCost = orderPrice + shipingCharge + totCharge;
            jLabel_TotCost.setText(String.valueOf(totOrderCost));

            SuppliedOrder so = new SuppliedOrder();
            boolean result = so.addOrderCost(orderID, totOrderCost);

            if (result) {
                for (int i = 0; i < 10000000; i++);
                JOptionPane.showMessageDialog(this, "Order Cost is successfully added to the database!");
            } else {
                JOptionPane.showMessageDialog(this, "Error of sending the order cost to the database!");
            }

        }

    }//GEN-LAST:event_jButton_CalcCostActionPerformed

    private void jTextField_ShModeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShModeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShModeNameActionPerformed

    private void jButton_CalcSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcSellingActionPerformed
        // TODO add your handling code here:

        profitMargin = Double.parseDouble(jTextField_ProfitMrgn.getText().toString());

        Vector<Vector<String>> modelsVector = new Vector<Vector<String>>();
        Vector<String> models = new Vector<String>();
        Vector<Vector<String>> newVector = new Vector<Vector<String>>();

        SuppliedOrder so = new SuppliedOrder();
        modelsVector = so.getModelPrices(orderID);

        for (int i = 0; i < modelsVector.size(); i++) {

            models = modelsVector.get(i);
            String modelName = models.get(0);
            double boughtPrice = Double.parseDouble(models.get(1));
            System.out.println("Model Name is " + modelName);
            System.out.println(boughtPrice);

            double sellingPrice = (boughtPrice * (profitMargin + 100)) / 100;
            System.out.println("Selling Price is " + sellingPrice);
            double sellingProfit = sellingPrice - boughtPrice;

            boolean result = so.addSellingPrice(orderID, modelName, sellingPrice);

            if (!result) {
                JOptionPane.showMessageDialog(this, "Error of sending the selling price of " + modelName + " to the database");
                break;
            }

            models.add(String.valueOf(sellingPrice) + 0);
            models.add(String.valueOf(sellingProfit) + 0);
            newVector.add(models);
        }

        jTable_ModelPrice.setModel(new DefaultTableModel(newVector, headers));
    }//GEN-LAST:event_jButton_CalcSellingActionPerformed

    private void jTextField_UnloadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UnloadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UnloadingActionPerformed

    private void jTextField_TransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TransportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TransportActionPerformed

    private void jComboBox_OrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OrderIDActionPerformed
        // TODO add your handling code here:

        orderID = Integer.parseInt(jComboBox_OrderID.getSelectedItem().toString());

        ShippingDetails sd = new ShippingDetails();
        shipID = sd.getShipID(orderID);

        ShippingDetails sp = new ShippingDetails();
        shipingCharge = sp.getShippingCharge(orderID);

        SuppliedOrder so = new SuppliedOrder();
        orderPrice = so.getOrderPrice(orderID);

        jTextField3_CShipID.setText(shipID);
        jTextField_SOrderID.setText(String.valueOf(orderID));
        jTextField_OrderPrice.setText(String.valueOf(orderPrice));
        jTextField_shipCharge.setText(String.valueOf(shipingCharge));

    }//GEN-LAST:event_jComboBox_OrderIDActionPerformed

    private void jTextField_InsuranceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_InsuranceKeyPressed
        // TODO add your handling code here:
        keyTyped(jTextField_Insurance);
    }//GEN-LAST:event_jTextField_InsuranceKeyPressed

    private void jTextField_DutyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DutyKeyPressed
        // TODO add your handling code here:

        keyTyped(jTextField_Duty);
    }//GEN-LAST:event_jTextField_DutyKeyPressed

    private void jTextField_PayorderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PayorderKeyPressed
        // TODO add your handling code here:

        keyTyped(jTextField_Payorder);
    }//GEN-LAST:event_jTextField_PayorderKeyPressed

    private void jTextField_ClearingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ClearingKeyPressed
        // TODO add your handling code here:

        keyTyped(jTextField_Clearing);
    }//GEN-LAST:event_jTextField_ClearingKeyPressed

    private void jTextField_UnloadingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UnloadingKeyPressed
        // TODO add your handling code here:

        keyTyped(jTextField_Unloading);
    }//GEN-LAST:event_jTextField_UnloadingKeyPressed

    private void jTextField_TransportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TransportKeyPressed
        // TODO add your handling code here:
        keyTyped(jTextField_Transport);
    }//GEN-LAST:event_jTextField_TransportKeyPressed

    private void jTextField_OrderPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OrderPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OrderPriceActionPerformed

    private void jTextField_ShModeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShModeNameKeyReleased
        // TODO add your handling code here:

        if (!jTextField_ShModeName.getText().isEmpty() && !jTextField_ShModeName.getText().equals(" ")) {

            ResultSet rst;
            String modelName = jTextField_ShModeName.getText();
            int orderId = Integer.parseInt(jTextField_SOrderID.getText());
            SuppliedOrder so = new SuppliedOrder();


            rst = so.searchModel(orderId, modelName);
            showTable(rst);
        }
    }//GEN-LAST:event_jTextField_ShModeNameKeyReleased

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

        this.dispose();
        new importing().setVisible(true);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void fillComboBox() {

        ShippingDetails sd = new ShippingDetails();
        ArrayList orderIDs = sd.getShippedOrderIds();

        Iterator i = orderIDs.iterator();

        while (i.hasNext()) {

            jComboBox_OrderID.addItem(i.next());
        }

    }

    private void keyTyped(JTextField textBox) {

        textBox.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar()) && !(e.getKeyChar() == '.')) {
                    e.consume();
                }
            }
        });
    }

    private void showTable(ResultSet rst) {

        DefaultTableModel dtm = (DefaultTableModel) jTable_ModelPrice.getModel();
        int row = dtm.getRowCount();

        for (int i = 0; i < row; i++) {

            dtm.removeRow(0);
        }

        try {

            while (rst.next()) {

                Object ob[] = {rst.getString(1), rst.getString(2), rst.getString(3)};
                dtm.addRow(ob);
            }

        } catch (SQLException ex) {

            System.out.println(ex + "------------Failure of retriving data");
        }
    }

    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPrice().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CalcCost;
    private javax.swing.JButton jButton_CalcSelling;
    private javax.swing.JButton jButton_SearchModel;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_home;
    private javax.swing.JComboBox jComboBox_OrderID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_TotCost;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable_ModelPrice;
    private javax.swing.JTextField jTextField3_CShipID;
    private javax.swing.JTextField jTextField_Clearing;
    private javax.swing.JTextField jTextField_Duty;
    private javax.swing.JTextField jTextField_Insurance;
    private javax.swing.JTextField jTextField_OrderPrice;
    private javax.swing.JTextField jTextField_Payorder;
    private javax.swing.JTextField jTextField_ProfitMrgn;
    private javax.swing.JTextField jTextField_SOrderID;
    private javax.swing.JTextField jTextField_ShModeName;
    private javax.swing.JTextField jTextField_Transport;
    private javax.swing.JTextField jTextField_Unloading;
    private javax.swing.JTextField jTextField_shipCharge;
    // End of variables declaration//GEN-END:variables
}
