/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DATA.report;
import Data.CusOrder;
import Data.DBConnManager;
import Data.DB_Access;
import Data.SellingCombo;
import Data.Validator;
import GUI.Charge;
import Gui.Order_Process;
import gui.EmpMng.Home;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Eranga M
 */
public class Selling extends javax.swing.JFrame {

    ArrayList selMachine_name;
    ArrayList selUnit_price;
    ArrayList selQuantity;
    int count;     
    String ordid;
    boolean result ;
    Vector<Vector<String>> orderVector = new Vector<Vector<String>>();
    
    DB_Access dba =new DB_Access();
     
    DBConnManager dbm = new DBConnManager();
    
    SellingCombo sc = new SellingCombo();

    /**
     * Creates new form Selling
     */
    public Selling() {
        initComponents();
        
        txt_cost.setEnabled(false);
        txt_diliCharge.setEnabled(false);
        txt_orderAmt.setEnabled(false);
        tbl_item.setEnabled(false);
        
        jComboBox_CusName.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
        
        @Override
        public  void keyReleased(KeyEvent evt)
            {
            
                String name=jComboBox_CusName.getEditor().getItem().toString();
                
                if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                {
                    sc.filltextField(name);
                }
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8)
                {
                    jComboBox_CusName.setModel(sc.getList(name));
                    
                    if( jComboBox_CusName.getItemCount()>0)
                    {
                        jComboBox_CusName.showPopup();
                        if(evt.getKeyCode() !=8)
                        {
                            ((JTextComponent)jComboBox_CusName.getEditor().getEditorComponent()).select(name.length(),jComboBox_CusName.getEditor().getItem().toString().length());
                        }
                        else
                        {
                            jComboBox_CusName.getEditor().setItem(name);
                        }
                            
                    }
                    else
                    {
                        jComboBox_CusName.addItem(name);
                    }
                    
                }
                
            }
         });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox_CusName = new javax.swing.JComboBox();
        jButton_back = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        lbl_order_id = new javax.swing.JLabel();
        txt_orderid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_custName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_search = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_item = new javax.swing.JTable();
        txt_date = new javax.swing.JTextField();
        lbl_orderAmount = new javax.swing.JLabel();
        lbl_dilivary = new javax.swing.JLabel();
        lbl_cost = new javax.swing.JLabel();
        txt_orderAmt = new javax.swing.JTextField();
        txt_diliCharge = new javax.swing.JTextField();
        txt_cost = new javax.swing.JTextField();
        btn_calculate = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_payid = new javax.swing.JTextField();
        btn_view = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        radio_cash = new javax.swing.JRadioButton();
        radio_cheq = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_states = new javax.swing.JTextField();
        txt_bank = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_cheqNo = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        btn_cheq_search = new javax.swing.JButton();
        btn_cheq_update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_cheq_delete = new javax.swing.JButton();
        btn_cheq_clear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jComboBox_CusName.setEditable(true);
        jComboBox_CusName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox_CusName);
        jComboBox_CusName.setBounds(540, 270, 270, 30);

        jButton_back.setBackground(new java.awt.Color(0, 153, 204));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(1180, 640, 40, 33);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home);
        jButton_home.setBounds(1230, 640, 50, 35);

        lbl_order_id.setText("Order ID :");
        getContentPane().add(lbl_order_id);
        lbl_order_id.setBounds(420, 240, 100, 10);

        txt_orderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_orderidActionPerformed(evt);
            }
        });
        getContentPane().add(txt_orderid);
        txt_orderid.setBounds(540, 230, 270, 30);

        jLabel1.setText("Date :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 240, 50, 10);

        lbl_custName.setText("Customer Name :");
        getContentPane().add(lbl_custName);
        lbl_custName.setBounds(420, 280, 150, 10);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-170, 530, 1300, 0);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(862, 170, 10, 550);

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_search.setText("Search");
        btn_search.setPreferredSize(new java.awt.Dimension(59, 23));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(930, 220, 140, 40);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setPreferredSize(new java.awt.Dimension(59, 23));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(930, 260, 140, 40);

        tbl_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Machine Name", "unit price", "quantity", "amount"
            }
        ));
        jScrollPane2.setViewportView(tbl_item);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 330, 700, 110);

        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_date);
        txt_date.setBounds(110, 230, 270, 30);

        lbl_orderAmount.setText("Order Amount :");
        getContentPane().add(lbl_orderAmount);
        lbl_orderAmount.setBounds(30, 480, 110, 10);

        lbl_dilivary.setText("Dilivary Charges :");
        getContentPane().add(lbl_dilivary);
        lbl_dilivary.setBounds(310, 480, 150, 13);

        lbl_cost.setText("Total Cost :");
        getContentPane().add(lbl_cost);
        lbl_cost.setBounds(590, 480, 140, 10);
        getContentPane().add(txt_orderAmt);
        txt_orderAmt.setBounds(120, 470, 160, 30);
        getContentPane().add(txt_diliCharge);
        txt_diliCharge.setBounds(410, 470, 150, 30);

        txt_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_costActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cost);
        txt_cost.setBounds(658, 470, 150, 30);

        btn_calculate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_calculate.setText("Calculate Amount");
        btn_calculate.setPreferredSize(new java.awt.Dimension(59, 23));
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calculate);
        btn_calculate.setBounds(930, 390, 140, 40);

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_print.setText("Print Invoice");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print);
        btn_print.setBounds(930, 650, 140, 40);

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cancel.setText("Cancel payment");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel);
        btn_cancel.setBounds(930, 610, 140, 40);

        btn_confirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_confirm.setText("Confirm payment");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirm);
        btn_confirm.setBounds(930, 570, 140, 40);

        jLabel2.setText("Pay ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 280, 60, 10);
        getContentPane().add(txt_payid);
        txt_payid.setBounds(110, 270, 270, 30);

        btn_view.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view);
        btn_view.setBounds(930, 180, 140, 40);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(-20, 550, 1150, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Pament Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(940, 450, 80, 14);

        buttonGroup1.add(radio_cash);
        radio_cash.setText("cash");
        radio_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cashActionPerformed(evt);
            }
        });
        getContentPane().add(radio_cash);
        radio_cash.setBounds(930, 470, 100, 21);

        buttonGroup1.add(radio_cheq);
        radio_cheq.setText("cheque");
        radio_cheq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cheqActionPerformed(evt);
            }
        });
        getContentPane().add(radio_cheq);
        radio_cheq.setBounds(930, 500, 120, 21);

        jLabel4.setText("Bank Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 570, 130, 30);

        jLabel5.setText("Cheque No:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 610, 130, 20);

        jLabel6.setText("Amount :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 640, 110, 20);

        jLabel7.setText("States :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 670, 50, 20);
        getContentPane().add(txt_states);
        txt_states.setBounds(100, 660, 260, 30);

        txt_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bankActionPerformed(evt);
            }
        });
        getContentPane().add(txt_bank);
        txt_bank.setBounds(100, 570, 260, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 0, 1280, 150);
        getContentPane().add(txt_cheqNo);
        txt_cheqNo.setBounds(100, 600, 260, 30);
        getContentPane().add(txt_amount);
        txt_amount.setBounds(100, 630, 260, 30);

        btn_cheq_search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cheq_search.setText("Search");
        btn_cheq_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cheq_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cheq_search);
        btn_cheq_search.setBounds(380, 610, 130, 40);

        btn_cheq_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cheq_update.setText("Update");
        btn_cheq_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cheq_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cheq_update);
        btn_cheq_update.setBounds(380, 570, 130, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(1300, 180));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-460, -10, 1790, 170);

        btn_cheq_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cheq_delete.setText("Delete");
        btn_cheq_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cheq_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cheq_delete);
        btn_cheq_delete.setBounds(510, 570, 130, 40);

        btn_cheq_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cheq_clear.setText("Clear");
        btn_cheq_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cheq_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cheq_clear);
        btn_cheq_clear.setBounds(510, 610, 130, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1130, 160, 180, 1200);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 310, 1120, 10);

        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Demo insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 670, 150, 21);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("SELLING PRODUCT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 184, 190, 20);

        jButton3.setForeground(new java.awt.Color(255, 153, 153));
        jButton3.setText("Demo Ceq Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 610, 150, 21);

        jButton2.setForeground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Demo Cheq Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 580, 150, 21);

        jButton4.setForeground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Demo Customer Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 640, 150, 21);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Delivery Charge");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(930, 340, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_orderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_orderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_orderidActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //set the system date to txt field
      
        radio_cash.setSelected(true);
        enable_payCntrols(false);
              
               
         Calendar cal = Calendar.getInstance();
         cal.add(Calendar.DATE, 1);
         SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
         String formatted = format1.format(cal.getTime());
        txt_date.setText(formatted);
  

        txt_orderid.setText(ordid);//get order id from previous form
        
        String Order_id=txt_orderid.getText();
        int  ordid=Integer.parseInt(Order_id);
        
        DefaultTableModel dtm=(DefaultTableModel)tbl_item.getModel();
            int row=dtm.getRowCount();

                for(int i=0; i<row; i++)
                {
                    dtm.removeRow(0);
                }
      
      for(int i=0; i<count; i++) {
        Object ob[]={selMachine_name.get(i), selUnit_price.get(i),selQuantity.get(i)};
        dtm.addRow(ob);
      }
       
    }//GEN-LAST:event_formWindowOpened

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       
       
        
        if (txt_orderid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please insert Order ID !!!", null, 2);
        }
        else {
            try {
            // get order id from txt field and convert string order id to int order id
            ordid = txt_orderid.getText();
            int Order_ID = Integer.parseInt(ordid);


            ResultSet rs = dba.getData("SELECT p.payID,p.payDate,p.payAmount,p.cusName,od.deliveryCost ,o.orderAmount FROM payment p,customer_order o, order_delivery od WHERE p.cusOrderID=o.cusOrderID and p.cusOrderID=od.cusOrderID and p.cusOrderID='"+Order_ID+"'");
            
//           if(!rs.next())
//               JOptionPane.showMessageDialog(null, "Order ID not found !!!", null, 2);
//           else
//               rs.beforeFirst();
           
            while (rs.next()) {
                txt_payid.setText(rs.getString(1));
                txt_date.setText(rs.getString(2));
                txt_cost.setText(rs.getString(3));
                jComboBox_CusName.setSelectedItem(rs.getString(4));
                txt_diliCharge.setText(rs.getString(5));
                txt_orderAmt.setText(String.valueOf(rs.getDouble(6)));
              
                //display values using txt field
            }
            
            CusOrder co = new CusOrder();
            rs = co.getOrderDetails(Order_ID);
            
            DefaultTableModel dtm=(DefaultTableModel)tbl_item.getModel();
            int row=dtm.getRowCount();

                for(int i=0; i<row; i++)
                {
                    dtm.removeRow(0);
                }
      
            while(rs.next()) {
                
                Object ob[]={rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                dtm.addRow(ob);
            
            }
            
            rs = co.getCusDetails(Order_ID);
            
            while(rs.next()) {
                
                txt_orderAmt.setText(rs.getString(1));
                txt_cost.setText(rs.getString(2));
                txt_diliCharge.setText(rs.getString(3));
            }
            
        } catch (SQLException ex) {
             System.out.println(ex);
             JOptionPane.showMessageDialog(null, "Error in searching data...!", null, 2);
        }
        
        } 

    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed

        // TODO add your handling code here:
        // get order id from txt field and convert string order id to int order id
         int reply=0;
         if (txt_orderid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please insert Order ID !!!", null, 2);
        }
         
         else {
             
            if(txt_diliCharge.getText().isEmpty())
                reply = JOptionPane.showConfirmDialog(this, "Do yoy want to add delivery charges","Delivery charges", JOptionPane.YES_NO_OPTION);
            
            if(reply == JOptionPane.YES_NO_OPTION) {
                
//                Charge ch = new Charge();
//                ch.setVisible(true);
            }
                
            ordid = txt_orderid.getText();
            int Order_ID = Integer.parseInt(ordid);
        
            //column 2=> unit price, column 3=> Quantity
            int col = 1;
            double grd_tot = 0;

            //to access the jtable value use a for loop
            for (int row = 0; row < tbl_item.getRowCount(); row++) {
                //get values from jtable
                String unit_price = tbl_item.getValueAt(row, col).toString();
                String quantity = tbl_item.getValueAt(row, col+1).toString();

                //convert string type values to integer and double
                double Unit_Price = Double.parseDouble(unit_price);
                double Quantity = Double.parseDouble(quantity);

                //calculate row amount
                double Amount = Unit_Price * Quantity;

                //set row amount valus to the jatable
                tbl_item.setValueAt(Amount, row, col + 2);

                //calculate the grand total
                grd_tot = grd_tot + Amount;

            }

            //set grand total to the jtext field
            String Grd_tot = Double.toString(grd_tot);
            txt_orderAmt.setText(Grd_tot);


        //.....................................................................


//        try {
//            //get dilivary charge fro database according to given order id
//            ResultSet rs = dba.getData("SELECT deliveryCost FROM order_delivery WHERE cusOrderID='" + ordid+ "'");
//            while (rs.next()) {
//                //txt_diliCharge.setText(rs.getString(1));
//                txt_diliCharge.setText("6500");
//            }
//        } catch (SQLException ex) {
//           JOptionPane.showMessageDialog(null, "Database Error", null, 2);
//        }
        
            txt_diliCharge.setText("6500");

            //get values from diliCharge text field and convert to double
            String qri_chag = txt_diliCharge.getText();
            double Qri_chag = Double.parseDouble(qri_chag);
       
            //calculate total cost and set it to txt_cost text field
            double Total_amt = grd_tot + Qri_chag;
            txt_cost.setText(String.valueOf(Total_amt));
            
         }



    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_date.setText(null);
        txt_orderid.setText(null);
       // jComboBox_CusName.setText(null);
        txt_orderAmt.setText(null);
        txt_diliCharge.setText(null);
        txt_cost.setText(null);
        txt_payid.setText(null);
        

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here:
        if ((txt_orderid.getText().isEmpty())&&(txt_date.getText().isEmpty())&&(txt_amount.getText().isEmpty())&&(txt_bank.getText().isEmpty()
                 && (txt_cheqNo.getText().isEmpty())&&(txt_cost.getText().isEmpty())&&(jComboBox_CusName.getSelectedItem().toString().isEmpty())&&(txt_orderAmt.getText().isEmpty())&&
                 (txt_payid.getText().isEmpty())&&(txt_states.getText().isEmpty())))
                 
            JOptionPane.showMessageDialog(null, "Values are not filled in Text Field !!!", null, 2);
        
        else {
        String date=String.valueOf(txt_date.getText());
        int order_id=Integer.parseInt(txt_orderid.getText());
        String cus_name=String.valueOf(jComboBox_CusName.getSelectedItem().toString());
        Double order_amt=Double.parseDouble(txt_orderAmt.getText());
        Double cost=Double.parseDouble(txt_cost.getText());
        int payid=Integer.parseInt(txt_payid.getText());
        
        //chque payment
                
        String bank=String.valueOf(txt_bank.getText());
        int cheq_no=Integer.parseInt(txt_cheqNo.getText());
        double amount=Double.parseDouble(txt_amount.getText());
        String states=String.valueOf(txt_states.getText());
        
        getTableValues();
        
        CusOrder co = new CusOrder();
        boolean result  = co.addOrder(order_id, orderVector);
        
        if(result)
            JOptionPane.showMessageDialog(this, "Order details are saved in the database");
        else
            //JOptionPane.showMessageDialog(this, "Error in inserting Order details!!"); 
            
        try 
        {
            dba.setData("update customer_order set orderAmount='" +  order_amt+ "',orderDate='" +  date+ "' where cusOrderID='" + order_id+ "'");
        } catch (SQLException ex) {
           // Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Database Error for Insert", null, 2);
        }
        
        
        try 
        {
            dba.setData("insert into payment (payID,payDate,payAmount,cusOrderID,cusName)values('" + payid + "','" + date+ "','" + cost + "','" + order_id+ "','" + cus_name+ "')");
        } catch (SQLException ex) {
            //Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println(ex);
             JOptionPane.showMessageDialog(null, "Database Error for Insert", null, 2);
        }
        
         try 
        {
            dba.setData("insert into cheque_payment (payID,chequeNo,bank,chequeAmount,status)values('" + payid + "','" + cheq_no + "','" + bank + "','" + amount+ "','" + states + "')");
            JOptionPane.showMessageDialog(this, "confirm!!!", null, 2);
        } catch (SQLException ex) {
            //Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println(ex);
             JOptionPane.showMessageDialog(null, "Database Error for Insert", null, 2);
        }
        
        }
          
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        
        txt_payid.setText("333");
        ordid = txt_orderid.getText();
        int Order_ID = Integer.parseInt(ordid);
         
        try 
        {
            ResultSet rs = dba.getData("SELECT cusName FROM customer WHERE cusOrderID='"+Order_ID+"'");
             while (rs.next())
             {
                              jComboBox_CusName.setSelectedItem(rs.getString(1));
             }
        } 
        catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_cheq_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cheq_searchActionPerformed
       
            // TODO add your handling code here:
        if (txt_payid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please insert Pay ID !!!", null, 2);
        }
           String payid = txt_payid.getText();
           int pay_id = Integer.parseInt(payid);
           
           
       try {
            ResultSet rs = dba.getData("SELECT chequeNo,bank,chequeAmount,status FROM cheque_payment WHERE payID='"+pay_id+"'");
                while (rs.next()) {
                    txt_cheqNo.setText(rs.getString(1));
                    txt_bank.setText(rs.getString(2));
                   txt_amount.setText(String.valueOf(rs.getDouble(3)));
                   txt_states.setText(rs.getString(4));
                   }
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error in Database !!!", null, 2);
        }
       
       
       
    }//GEN-LAST:event_btn_cheq_searchActionPerformed

    private void btn_cheq_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cheq_deleteActionPerformed
       
            // TODO add your handling code here:
            String payid = txt_payid.getText();
           int pay_id = Integer.parseInt(payid);
           
         try {
            dba.setData("delete from cheque_payment  where payID='"+pay_id+"'");
            
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Please insert Pay ID !!!", null, 2);
        }
    }//GEN-LAST:event_btn_cheq_deleteActionPerformed

    private void btn_cheq_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cheq_clearActionPerformed
        // TODO add your handling code here:
        txt_bank.setText(null);
        txt_cheqNo.setText(null);
        txt_amount.setText(null);
        txt_states.setText(null);
    }//GEN-LAST:event_btn_cheq_clearActionPerformed

    private void btn_cheq_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cheq_updateActionPerformed
        // TODO add your handling code here:
       String payid = txt_payid.getText();
       int pay_id = Integer.parseInt(payid);
        
        String bank=String.valueOf(txt_bank.getText());
        int cheq_no=Integer.parseInt(txt_cheqNo.getText());
        double amount=Double.parseDouble(txt_amount.getText());
        String states=String.valueOf(txt_states.getText());
        
        try 
        {
            dba.setData("update cheque_payment set chequeNo='"+ cheq_no +"', bank='" + bank+ "',chequeAmount='" + amount + "',status='"+states+"' where payID='" + pay_id+ "'");
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cheq_updateActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
         String payid = txt_payid.getText();
           int pay_id = Integer.parseInt(payid);
           
           ordid = txt_orderid.getText();
        int Order_ID = Integer.parseInt(ordid);
           
         try {
            dba.setData("delete from cheque_payment  where payID='"+pay_id+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
         
          try {
            dba.setData("delete from payment  where payID='"+pay_id+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
           try {
            dba.setData("delete orderAmount,orderDate from cheque_payment  where cusOrderID='"+Order_ID+"'");
            JOptionPane.showMessageDialog(this, "payment cancel!!!", null, 2);
        } catch (SQLException ex) {
            Logger.getLogger(Selling.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void radio_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cashActionPerformed
        // TODO add your handling code here:
        
        radio_cash.setSelected(true);
         enable_payCntrols(false);
       
       
        
    }//GEN-LAST:event_radio_cashActionPerformed

    private void radio_cheqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cheqActionPerformed
        // TODO add your handling code here:
       // radio_cheq.setSelected(true);
        
        enable_payCntrols(true);
        
        
       
        
    }//GEN-LAST:event_radio_cheqActionPerformed

    public void enable_payCntrols(boolean isEnable)
    {
     
        txt_bank.setEditable(isEnable);
        txt_cheqNo.setEditable(isEnable);
        txt_amount.setEditable(isEnable);
        txt_states.setEditable(isEnable);
        btn_cheq_update.setEnabled(isEnable);
        btn_cheq_delete.setEnabled(isEnable);
        btn_cheq_search.setEnabled(isEnable);
        btn_cheq_clear.setEnabled(isEnable);
        
    }
    private void txt_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bankActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txt_orderid.setText("6");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_bank.setText("BOC");
        txt_cheqNo.setText("345987");
        txt_amount.setText("40000.00");
        txt_states.setText("remain");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txt_payid.setText("102");
        txt_orderid.setText("7");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txt_cheqNo.setText("273687");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        Charge ch = new Charge();
//        ch.setVisible(true);
        
        txt_diliCharge.setText("5000");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        if (txt_orderid.getText().isEmpty()) 
            JOptionPane.showMessageDialog(null, "Please insert Order ID !!!", null, 2);
        else {
            try {
            // TODO add your handling code here:

            HashMap para = new HashMap();

            para.put("orderID", Integer.parseInt(txt_orderid.getText().toString()));

            report show = new report("E:\\PROJECT\\Riyoma System\\src\\IReports\\SelInvoice.jasper", para);
            show.setVisible(true);
        } catch (JRException ex) {
           System.out.println(ex);
        } catch (ClassNotFoundException ex) {
           System.out.println(ex);
        } catch (SQLException ex) {
           System.out.println(ex);
        }
        }
            
        
    }//GEN-LAST:event_btn_printActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

        close();
        new Order_Process().setVisible(true); 

    }//GEN-LAST:event_jButton_backActionPerformed

    public void setSellOrderDetails(ArrayList selmachineName, ArrayList selunitPrice,ArrayList selquanity, int count) {      
            
        selMachine_name = selmachineName;
        selUnit_price= selunitPrice;
        selQuantity=selquanity;
        this.count = count;
    }
    
    public void setOrderId(String orderid)
    {
        ordid=orderid;
    }
    
    public void getTableValues() {
         
        for(int i=0; i<count; i++) {
            
            Vector<String> orders = new Vector<String>();
            orders.add(tbl_item.getValueAt(i, 0).toString());
            orders.add(tbl_item.getValueAt(i, 1).toString());
            orders.add(tbl_item.getValueAt(i, 2).toString());
            orders.add(tbl_item.getValueAt(i, 3).toString());
            
            orderVector.add(orders);
        }
    }
    
    public void addDeliveryCharge() {
        
        //txt_diliCharge.setText(String.valueOf(delCharge));
        int orderID = Integer.parseInt(txt_orderid.getText());
        
        try {
            ResultSet rs = dba.getData("select deliveryCost from order_delivery where cusOrderID='"+orderID+"'");
            if(rs.next())
                txt_diliCharge.setText(rs.getString(1));
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cheq_clear;
    private javax.swing.JButton btn_cheq_delete;
    private javax.swing.JButton btn_cheq_search;
    private javax.swing.JButton btn_cheq_update;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_view;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_home;
    private javax.swing.JComboBox jComboBox_CusName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JLabel lbl_custName;
    private javax.swing.JLabel lbl_dilivary;
    private javax.swing.JLabel lbl_orderAmount;
    private javax.swing.JLabel lbl_order_id;
    private javax.swing.JRadioButton radio_cash;
    private javax.swing.JRadioButton radio_cheq;
    private javax.swing.JTable tbl_item;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bank;
    private javax.swing.JTextField txt_cheqNo;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_diliCharge;
    private javax.swing.JTextField txt_orderAmt;
    private javax.swing.JTextField txt_orderid;
    private javax.swing.JTextField txt_payid;
    private javax.swing.JTextField txt_states;
    // End of variables declaration//GEN-END:variables




}