/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.ShippingDetails;
import Data.SuppliedOrder;
import Data.Validator;
import gui.EmpMng.Home;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Senali
 */
public class Shipping extends javax.swing.JFrame {

    boolean shipping;
    String shipID; 
    String shipCompany;
    String shipAddress;
    String email;
    String shipName;
    int shipOrderID;
    String shippedDate;
    String landingDate;
    double shipCharge;
    
    
    /**
     * Creates new form 
     */
    public Shipping() {
        initComponents();
        
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_back = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ShipID = new javax.swing.JTextField();
        jTextField_ShipCompany = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ShipAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_SearchShipID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ShipOrder = new javax.swing.JTable();
        jButton_ClearShip = new javax.swing.JButton();
        jButton_RemoveShip = new javax.swing.JButton();
        jButton_UpdateShip = new javax.swing.JButton();
        jButton_AddShip = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jTextField_ShipName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_ShippedDate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField_LandingDate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_ShipCharge = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton_Date = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Shipping = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jTextField_SearchSOrderID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jRadioButton_shipping = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton_shiporder = new javax.swing.JRadioButton();
        jComboBox_SOrderID = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField_OshipID = new javax.swing.JTextField();
        jButton_Date1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1280, 150);

        jButton_back.setBackground(new java.awt.Color(0, 153, 204));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(1160, 630, 50, 33);

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home);
        jButton_home.setBounds(1220, 630, 50, 35);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 160);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1130, 160, 170, 540);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Shipped-Order Details");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 220, 150, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Shipping Details Management");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 180, 250, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Ship Id : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 250, 90, 15);

        jTextField_ShipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShipIDActionPerformed(evt);
            }
        });
        jTextField_ShipID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ShipIDKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_ShipID);
        jTextField_ShipID.setBounds(150, 240, 230, 30);

        jTextField_ShipCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShipCompanyActionPerformed(evt);
            }
        });
        jTextField_ShipCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ShipCompanyKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_ShipCompany);
        jTextField_ShipCompany.setBounds(150, 290, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Company : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 300, 90, 15);

        jTextField_ShipAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShipAddressActionPerformed(evt);
            }
        });
        jTextField_ShipAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ShipAddressKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_ShipAddress);
        jTextField_ShipAddress.setBounds(150, 340, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 350, 110, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("E-mail : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 450, 110, 15);

        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_Email);
        jTextField_Email.setBounds(150, 440, 230, 30);

        jTextField_SearchShipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchShipIDActionPerformed(evt);
            }
        });
        jTextField_SearchShipID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchShipIDKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_SearchShipID);
        jTextField_SearchShipID.setBounds(150, 510, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ship Id :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 520, 70, 15);

        jTable_ShipOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order Id", "ShipID", "Shipped Date", "Landing Date", "Charge"
            }
        ));
        jTable_ShipOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ShipOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ShipOrder);
        if (jTable_ShipOrder.getColumnModel().getColumnCount() > 0) {
            jTable_ShipOrder.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(590, 550, 540, 120);

        jButton_ClearShip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ClearShip.setText("Clear");
        jButton_ClearShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearShipActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ClearShip);
        jButton_ClearShip.setBounds(520, 420, 80, 30);

        jButton_RemoveShip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_RemoveShip.setText("Remove");
        jButton_RemoveShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveShipActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RemoveShip);
        jButton_RemoveShip.setBounds(520, 370, 80, 30);

        jButton_UpdateShip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_UpdateShip.setText("Update");
        jButton_UpdateShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateShipActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_UpdateShip);
        jButton_UpdateShip.setBounds(520, 320, 80, 30);

        jButton_AddShip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_AddShip.setText("Insert");
        jButton_AddShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddShipActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AddShip);
        jButton_AddShip.setBounds(520, 270, 80, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(810, 230, 210, 10);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Ship Name : ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 400, 110, 15);

        jTextField_ShipName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShipNameActionPerformed(evt);
            }
        });
        jTextField_ShipName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ShipNameKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_ShipName);
        jTextField_ShipName.setBounds(150, 390, 230, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Shipped Date : ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(680, 350, 110, 15);

        jTextField_ShippedDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ShippedDateMouseClicked(evt);
            }
        });
        jTextField_ShippedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShippedDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ShippedDate);
        jTextField_ShippedDate.setBounds(790, 340, 230, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Landing Date : ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(680, 400, 110, 15);

        jTextField_LandingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LandingDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_LandingDate);
        jTextField_LandingDate.setBounds(790, 390, 230, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Shipping Charge : ");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(680, 450, 110, 15);

        jTextField_ShipCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShipChargeActionPerformed(evt);
            }
        });
        jTextField_ShipCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ShipChargeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_ShipCharge);
        jTextField_ShipCharge.setBounds(820, 440, 200, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("Ex: name123@gmail.com");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(150, 470, 170, 20);

        jButton_Date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Date.setText("Select");
        jButton_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Date);
        jButton_Date.setBounds(1030, 390, 80, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("Rs.");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(790, 450, 20, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Order Id : ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(680, 250, 100, 15);

        jTable_Shipping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ship Id", "Company", "Address", "Ship Name", "Email"
            }
        ));
        jTable_Shipping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ShippingMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Shipping);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 550, 580, 120);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Order Id : ");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(720, 520, 60, 15);

        jTextField_SearchSOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchSOrderIDActionPerformed(evt);
            }
        });
        jTextField_SearchSOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchSOrderIDKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_SearchSOrderID);
        jTextField_SearchSOrderID.setBounds(790, 510, 150, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ship-Company Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 250, 17);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(170, 230, 210, 10);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 510, 80, 30);

        jRadioButton_shipping.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_shipping.setSelected(true);
        jRadioButton_shipping.setText("Ship-Company");
        jRadioButton_shipping.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton_shipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_shippingActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_shipping);
        jRadioButton_shipping.setBounds(410, 200, 110, 23);
        jRadioButton_shipping.getAccessibleContext().setAccessibleName("Shipping");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Select one Option :");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(370, 180, 120, 20);

        jRadioButton_shiporder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_shiporder.setText("Shipped-Order");
        jRadioButton_shiporder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_shiporderActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_shiporder);
        jRadioButton_shiporder.setBounds(530, 200, 110, 23);

        getContentPane().add(jComboBox_SOrderID);
        jComboBox_SOrderID.setBounds(790, 240, 230, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("View All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 510, 80, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Ship ID :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(680, 300, 110, 15);

        jTextField_OshipID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_OshipIDMouseClicked(evt);
            }
        });
        jTextField_OshipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OshipIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_OshipID);
        jTextField_OshipID.setBounds(790, 290, 230, 30);

        jButton_Date1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Date1.setText("Select");
        jButton_Date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Date1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Date1);
        jButton_Date1.setBounds(1030, 340, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 470, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ShipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShipIDActionPerformed

    private void jTextField_ShipCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShipCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShipCompanyActionPerformed

    private void jTextField_ShipAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShipAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShipAddressActionPerformed

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_SearchShipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchShipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchShipIDActionPerformed

    private void jButton_ClearShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearShipActionPerformed
        // TODO add your handling code here:
        jTextField_Email.setText("");
        jTextField_LandingDate.setText("");
        jTextField_OshipID.setText("");
        jTextField_SearchSOrderID.setText("");
        jTextField_SearchShipID.setText("");
        jTextField_ShipAddress.setText("");
        jTextField_ShipCharge.setText("");
        jTextField_ShipCompany.setText("");
        jTextField_ShipID.setText("");
        jTextField_ShipName.setText("");
        jTextField_ShippedDate.setText("");
    }//GEN-LAST:event_jButton_ClearShipActionPerformed

    private void jButton_RemoveShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveShipActionPerformed
        // TODO add your handling code here:
        
        if(shipping) {
            
            shipID = jTable_Shipping.getValueAt(0, 0).toString();
            
            ShippingDetails sd = new ShippingDetails();
            boolean result = sd.removeShipCompany(shipID);
            
            if(result) {
                JOptionPane.showMessageDialog(this, "Deletion is Successful!");
                
                ResultSet rst = sd.getShipCompanies();
                showTable(rst, true);
            }
            else
                JOptionPane.showMessageDialog(this, "Deletion is not Successful!");
                   
        }
        
        else {
            
            shipOrderID = Integer.parseInt(jTable_ShipOrder.getValueAt(0, 0).toString());
            
            ShippingDetails sd = new ShippingDetails();
            boolean result = sd.removeShippedOrder(shipOrderID);
            
            if(result) {
                JOptionPane.showMessageDialog(this, "Deletion is Successful!");
                
                ResultSet rst = sd.getAllshippedOrders();
                showTable(rst, false);
            }
            else
                JOptionPane.showMessageDialog(this, "Deletion is not Successful!");
        }
    }//GEN-LAST:event_jButton_RemoveShipActionPerformed

    private void jButton_UpdateShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateShipActionPerformed
        // TODO add your handling code here:
        if(shipping) {
            
            if(jTextField_Email.getText().isEmpty() || jTextField_ShipAddress.getText().isEmpty() || jTextField_ShipID.getText().isEmpty()
               || jTextField_ShipCompany.getText().isEmpty() || jTextField_ShipName.getText().isEmpty()) {
                
                    JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");                    
            } 
            else {
                shipID = jTextField_ShipID.getText().toString();
                shipCompany = jTextField_ShipCompany.getText().toString();
                shipAddress = jTextField_ShipAddress.getText().toString();
                email = jTextField_Email.getText().toString();
                shipName = jTextField_ShipName.getText().toString();
            
                ShippingDetails sd = new ShippingDetails(shipID, shipCompany, shipName, shipAddress, email);
                boolean result = sd.updateShipCompanyDetails();
            
                if(result) {
                    JOptionPane.showMessageDialog(this, "Updating is Successful!");
                
                    ResultSet rst = sd.searchShipCompany(shipID);
                    showTable(rst, true);
                }
                else
                    JOptionPane.showMessageDialog(this, "Updating is not Successful!");
            
                    jTextField_ShipID.setEnabled(true);
            
            }
            
        }
        
        else {
            
            if(jTextField_OshipID.getText().isEmpty() || jTextField_LandingDate.getText().isEmpty() || 
                    jTextField_ShippedDate.getText().isEmpty() || jTextField_ShipCharge.getText().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");      
            }
            else {
            
                shipOrderID = Integer.parseInt(jComboBox_SOrderID.getSelectedItem().toString());
                shipID = jTextField_OshipID.getText().toString();
                shippedDate = jTextField_ShippedDate.getText().toString();
                landingDate = jTextField_LandingDate.getText().toString();
                shipCharge = Double.parseDouble(jTextField_ShipCharge.getText().toString());
                
                ShippingDetails sd = new ShippingDetails(shipID, shipOrderID, shippedDate, landingDate, shipCharge);
                boolean result = sd.updateShippedOrders();
                
                if(result) {
                        
                        JOptionPane.showMessageDialog(this, "Updation is Successful!");
                        
                        ResultSet rst  = sd.searchShippedOrders(shipOrderID);
                        showTable(rst, false);
                    } 
                    else
                        JOptionPane.showMessageDialog(this, "Updation is not Successful!");
                
                jComboBox_SOrderID.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton_UpdateShipActionPerformed

    private void jButton_AddShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddShipActionPerformed
        // TODO add your handling code here:
        if(shipping) {
            
            if(jTextField_Email.getText().isEmpty() || jTextField_ShipAddress.getText().isEmpty() || jTextField_ShipID.getText().isEmpty()
               || jTextField_ShipCompany.getText().isEmpty() || jTextField_ShipName.getText().isEmpty()) {
                
                    JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");                    
            } 
            else {
                    
                    shipID = jTextField_ShipID.getText().toString();
                    shipCompany = jTextField_ShipCompany.getText().toString();
                    shipAddress = jTextField_ShipAddress.getText().toString();
                    email = jTextField_Email.getText().toString();
                    shipName = jTextField_ShipName.getText().toString();
                    
                    ShippingDetails sd = new ShippingDetails(shipID, shipCompany, shipName, shipAddress, email);
                    
                    boolean result = sd.addShipCompanyDetails();
                    
                    if(result) {
                        
                        JOptionPane.showMessageDialog(this, "Insertion is Successful!");
                        
                        ResultSet rst  = sd.searchShipCompany(shipID);
                        showTable(rst, true);
                        
                    } 
                    else
                        JOptionPane.showMessageDialog(this, "Insertion is not Successful!");
                    
                
            }
            
        }
        else {
            
            if(jTextField_OshipID.getText().isEmpty() || jTextField_LandingDate.getText().isEmpty() || 
                    jTextField_ShippedDate.getText().isEmpty() || jTextField_ShipCharge.getText().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, "Please fill the neccessary fields!");      
            }
            else {
                
                shipOrderID = Integer.parseInt(jComboBox_SOrderID.getSelectedItem().toString());
                shipID = jTextField_OshipID.getText().toString();
                shippedDate = jTextField_ShippedDate.getText().toString();
                landingDate = jTextField_LandingDate.getText().toString();
                shipCharge = Double.parseDouble(jTextField_ShipCharge.getText().toString());
                
                ShippingDetails sd = new ShippingDetails(shipID, shipOrderID, shippedDate, landingDate, shipCharge);
                boolean result = sd.addShippedOrders();
                
                if(result) {
                        
                        JOptionPane.showMessageDialog(this, "Insertion is Successful!");
                        
                        ResultSet rst  = sd.searchShippedOrders(shipOrderID);
                        showTable(rst, false);
                    } 
                    else
                        JOptionPane.showMessageDialog(this, "Insertion is not Successful!");
                
            }
        }
    }//GEN-LAST:event_jButton_AddShipActionPerformed

    private void jTextField_ShipNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShipNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShipNameActionPerformed

    private void jTextField_ShippedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShippedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShippedDateActionPerformed

    private void jTextField_ShipChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShipChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShipChargeActionPerformed

    private void jTextField_LandingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LandingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LandingDateActionPerformed

    private void jButton_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DateActionPerformed
        // TODO add your handling code here:
        
        gui.DatePicker dp = new gui.DatePicker(this);
        
        jTextField_LandingDate.setText(dp.setPickedDate());

    }//GEN-LAST:event_jButton_DateActionPerformed

    private void jTextField_ShippedDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ShippedDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShippedDateMouseClicked

    private void jTextField_SearchSOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchSOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchSOrderIDActionPerformed

    private void jTextField_ShipIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShipIDKeyPressed
        // TODO add your handling code here:
        
        jTextField_ShipID.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            if(!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar()=='.') && !(e.getKeyChar()=='-') && !(Character.isDigit(e.getKeyChar())))
                
                e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_ShipIDKeyPressed

    private void jRadioButton_shippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_shippingActionPerformed
        // TODO add your handling code here:

        setVisibility(true);

    }//GEN-LAST:event_jRadioButton_shippingActionPerformed

    private void jRadioButton_shiporderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_shiporderActionPerformed
        // TODO add your handling code here:

        setVisibility(false);
        
    }//GEN-LAST:event_jRadioButton_shiporderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
        setVisibility(true);
         
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ShippingDetails sd = new ShippingDetails();
        ResultSet rst = sd.getAllshippedOrders();
        
        showTable(rst, false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ShippingDetails sd = new ShippingDetails();
        ResultSet rst = sd.getShipCompanies();
        
        showTable(rst, true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable_ShippingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ShippingMouseClicked
        // TODO add your handling code here:
        
        int row = jTable_Shipping.getSelectedRow();
        
        if(jTable_Shipping.getRowSelectionAllowed()) {
            
            if(shipping) {
                jTextField_ShipID.setText(jTable_Shipping.getValueAt(row, 0).toString());
                jTextField_ShipCompany.setText(jTable_Shipping.getValueAt(row, 1).toString());
                jTextField_ShipAddress.setText(jTable_Shipping.getValueAt(row, 2).toString());
                jTextField_ShipName.setText(jTable_Shipping.getValueAt(row, 3).toString());
                jTextField_Email.setText(jTable_Shipping.getValueAt(row, 4).toString());
                
                jTextField_ShipID.setEnabled(false);
            }
            else {
                
                jTextField_OshipID.setText(jTable_Shipping.getValueAt(row, 0).toString());
            }
            
        }
        
    }//GEN-LAST:event_jTable_ShippingMouseClicked

    private void jTextField_SearchShipIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchShipIDKeyReleased
        // TODO add your handling code here:
        
         if(!jTextField_SearchShipID.getText().isEmpty() && !jTextField_SearchShipID.getText().equals(" ")) {
           
            ResultSet rst;
            shipID = jTextField_SearchShipID.getText();
            ShippingDetails sd = new ShippingDetails();
           
                rst = sd.searchShipCompany(shipID);
                showTable(rst, true);
                
                rst = sd.getShippedOrders(shipID);
                showTable(rst, false);
       }
    }//GEN-LAST:event_jTextField_SearchShipIDKeyReleased

    private void jTextField_OshipIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_OshipIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OshipIDMouseClicked

    private void jTextField_OshipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OshipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OshipIDActionPerformed

    private void jTextField_SearchSOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchSOrderIDKeyReleased
        // TODO add your handling code here:
        
        if(!jTextField_SearchSOrderID.getText().isEmpty() && !jTextField_SearchSOrderID.getText().equals(" ")) {
           
            ResultSet rst;
            shipOrderID = Integer.parseInt(jTextField_SearchSOrderID.getText().toString());
            ShippingDetails sd = new ShippingDetails();
          
            
            rst = sd.searchShippedOrders(shipOrderID);
            showTable(rst, false);
        }
    }//GEN-LAST:event_jTextField_SearchSOrderIDKeyReleased

    private void jTable_ShipOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ShipOrderMouseClicked
        // TODO add your handling code here:
        
        int row = jTable_ShipOrder.getSelectedRow();
        
        if(jTable_ShipOrder.getRowSelectionAllowed()) {
            
            jComboBox_SOrderID.setSelectedItem(jTable_ShipOrder.getValueAt(row, 0).toString());
            jTextField_OshipID.setText(jTable_ShipOrder.getValueAt(row, 1).toString());
            jTextField_ShippedDate.setText(jTable_ShipOrder.getValueAt(row, 2).toString());
            jTextField_LandingDate.setText(jTable_ShipOrder.getValueAt(row, 3).toString());
            jTextField_ShipCharge.setText(jTable_ShipOrder.getValueAt(row, 4).toString());
                
            jComboBox_SOrderID.setEnabled(false);
        }
    }//GEN-LAST:event_jTable_ShipOrderMouseClicked

    private void jButton_Date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Date1ActionPerformed
        // TODO add your handling code here:
        gui.DatePicker dp = new gui.DatePicker(this);
        
        jTextField_ShippedDate.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton_Date1ActionPerformed

    private void jTextField_ShipCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShipCompanyKeyPressed
        // TODO add your handling code here:
        
        jTextField_ShipCompany.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            if(!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar()=='.') && !(Character.isWhitespace(e.getKeyChar()))
               && !(e.getKeyChar()=='(') && !(e.getKeyChar()==')'))
                
                e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_ShipCompanyKeyPressed

    private void jTextField_ShipAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShipAddressKeyPressed
        // TODO add your handling code here:
        
        jTextField_ShipAddress.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            if(!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar()=='.') && !(Character.isWhitespace(e.getKeyChar()))
               && !(e.getKeyChar()=='(') && !(e.getKeyChar()==')') && !(e.getKeyChar()=='/') && !(e.getKeyChar()=='-') 
               && !(e.getKeyChar()==',') && !(Character.isDigit(e.getKeyChar())))
                
                e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_ShipAddressKeyPressed

    private void jTextField_ShipNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShipNameKeyPressed
        // TODO add your handling code here:
        
        jTextField_ShipName.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            if(!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar()=='-') && !(Character.isWhitespace(e.getKeyChar()))
               && !(Character.isDigit(e.getKeyChar())))
                
                e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_ShipNameKeyPressed

    private void jTextField_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyPressed
        // TODO add your handling code here:
        
        jTextField_Email.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            if(!Character.isLetter(e.getKeyChar()) && !(e.getKeyChar()=='.') && !(Character.isDigit(e.getKeyChar())) 
               && !(e.getKeyChar()=='@'))
                
                e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_EmailKeyPressed

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        // TODO add your handling code here:
        
        if(!jTextField_Email.getText().isEmpty())
        {
            Validator v = new Validator();
            boolean result = v.checkEmail(jTextField_Email.getText());
        
            if(!result)
                JOptionPane.showMessageDialog(this, "Invalid Email!");
        }
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jTextField_ShipChargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ShipChargeKeyPressed
        // TODO add your handling code here:
        
        jTextField_ShipCharge.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if(!Character.isDigit(e.getKeyChar()) && !(e.getKeyChar()=='.'))
                    e.consume();
        }
        });
    }//GEN-LAST:event_jTextField_ShipChargeKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField_Email.setText("");
        jTextField_LandingDate.setText("");
        jTextField_OshipID.setText("");
        jTextField_SearchSOrderID.setText("");
        jTextField_SearchShipID.setText("");
        jTextField_ShipAddress.setText("");
        jTextField_ShipCharge.setText("");
        jTextField_ShipCompany.setText("");
        jTextField_ShipID.setText("");
        jTextField_ShipName.setText("");
        jTextField_ShippedDate.setText("");
        
        DefaultTableModel dtm = (DefaultTableModel) jTable_Shipping.getModel();
        int row=dtm.getRowCount();
            
        for(int i=0; i<row; i++) {
                
            dtm.removeRow(0);    
        }
        
        dtm = (DefaultTableModel) jTable_ShipOrder.getModel();
        row=dtm.getRowCount();
            
        for(int i=0; i<row; i++) {
                
            dtm.removeRow(0);    
        }
        
        fillComboBox();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

        this.dispose();
        new importing().setVisible(true);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

     public void showTable(ResultSet rst, boolean shipping) {
        
        if(shipping) {
            
            DefaultTableModel dtm = (DefaultTableModel) jTable_Shipping.getModel();
            int row=dtm.getRowCount();
            
            for(int i=0; i<row; i++) {
                
                dtm.removeRow(0);    
            }
        
            try {
                
                while(rst.next()) {
                    
                Object ob[]={rst.getString(2), rst.getString(1), rst.getString(5), rst.getString(3), rst.getString(4)};
                dtm.addRow(ob);    
                }   
                
            } catch (SQLException ex) {
                
                System.out.println(ex + "------------Failure of retriving data");
            }
        }
        
        else {
            
            DefaultTableModel dtm = (DefaultTableModel) jTable_ShipOrder.getModel();
            int row=dtm.getRowCount();
            
            for(int i=0; i<row; i++) {
                
                dtm.removeRow(0);    
            }
        
            try {
                
                while(rst.next()) {
                    
                Object ob[]={rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5)};
                dtm.addRow(ob);    
                }   
                
            } catch (SQLException ex) {
                
                System.out.println(ex + "------------Failure of retriving data");
            }
        }
     }
 
     private void fillComboBox() {
         
         SuppliedOrder so = new SuppliedOrder();
         ArrayList orderIDs = so.getOrderIDs();
        
         Iterator i = orderIDs.iterator();
        
         while(i.hasNext()) {
            
            jComboBox_SOrderID.addItem(i.next());
         }
     }
     
     private void setVisibility(boolean isShip) {
         
        shipping = isShip;
        
        jTextField_LandingDate.setEnabled(!isShip);
        jTextField_ShipCharge.setEnabled(!isShip);
        jComboBox_SOrderID.setEnabled(!isShip);
        jTextField_ShippedDate.setEnabled(!isShip);
        jButton_Date.setEnabled(!isShip);
        jTextField_OshipID.setEnabled(false);
        jButton_Date1.setEnabled(!isShip);
        jLabel24.setEnabled(!isShip);
        jLabel25.setEnabled(!isShip);
        jLabel20.setEnabled(!isShip);
        jLabel21.setEnabled(!isShip);
        jLabel28.setEnabled(!isShip);
        jLabel22.setEnabled(!isShip);
        jLabel4.setEnabled(!isShip);
        
        jRadioButton_shiporder.setSelected(!isShip);
        
        jTextField_Email.setEnabled(isShip);
        jTextField_ShipAddress.setEnabled(isShip);
        jTextField_ShipCompany.setEnabled(isShip);
        jTextField_ShipName.setEnabled(isShip);
        jTextField_ShipID.setEnabled(isShip);
        jLabel6.setEnabled(isShip);
        jLabel7.setEnabled(isShip);
        jLabel8.setEnabled(isShip);
        jLabel19.setEnabled(isShip);
        jLabel12.setEnabled(isShip);
        jLabel5.setEnabled(isShip);
        jLabel23.setEnabled(isShip);
        
        jRadioButton_shipping.setSelected(isShip);
     }
     
     public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shipping().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_AddShip;
    private javax.swing.JButton jButton_ClearShip;
    private javax.swing.JButton jButton_Date;
    private javax.swing.JButton jButton_Date1;
    private javax.swing.JButton jButton_RemoveShip;
    private javax.swing.JButton jButton_UpdateShip;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_home;
    private javax.swing.JComboBox jComboBox_SOrderID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton_shiporder;
    private javax.swing.JRadioButton jRadioButton_shipping;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable_ShipOrder;
    private javax.swing.JTable jTable_Shipping;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_LandingDate;
    private javax.swing.JTextField jTextField_OshipID;
    private javax.swing.JTextField jTextField_SearchSOrderID;
    private javax.swing.JTextField jTextField_SearchShipID;
    private javax.swing.JTextField jTextField_ShipAddress;
    private javax.swing.JTextField jTextField_ShipCharge;
    private javax.swing.JTextField jTextField_ShipCompany;
    private javax.swing.JTextField jTextField_ShipID;
    private javax.swing.JTextField jTextField_ShipName;
    private javax.swing.JTextField jTextField_ShippedDate;
    // End of variables declaration//GEN-END:variables
}
