/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.EmpMng;

import data.Attend;
import Data.DBConnManager;
import Data.DB_Access;
import Data.EmployeeInfo;
import gui.DatePicker;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gallelaptop.lk
 */
public class Attendance extends javax.swing.JFrame {

    DB_Access dba = null;
    int check;
    int index = 0;
   
    public Attendance() {
        initComponents();
        
        dba = new DB_Access();
        
        readAttTable();
        readtable();
        fillLeaveseid();
        fillEname();
        control();
        jLabel_seid.setVisible(false);
        jLabel1_sname.setVisible(false);
        
        jTextField_dateL.setEditable(false);
        jTextField_dateL.setEnabled(false);
        jComboBox_empIDL.setEnabled(false);
        jButton_dateLe.setEnabled(false);
        jButton_deleteLeave.setEnabled(false);
        jButton_submitLeave.setEnabled(false);
        jButton_refreshL.setEnabled(false);
        jButton_searchL.setEnabled(false);
        jTable_leaves.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_seid = new javax.swing.JLabel();
        jLabel1_sname = new javax.swing.JLabel();
        jButton_home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_oIn = new javax.swing.JButton();
        jButton_cIn = new javax.swing.JButton();
        jButton_oOut = new javax.swing.JButton();
        jButton_cOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_showLeaves = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_dateL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_leaves = new javax.swing.JTable();
        jButton_refreshL = new javax.swing.JButton();
        jButton_dateLe = new javax.swing.JButton();
        jButton_submitLeave = new javax.swing.JButton();
        jButton_deleteLeave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_attend = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_empIDL = new javax.swing.JComboBox();
        jButton_searchL = new javax.swing.JButton();
        jComboBox_getempSrch = new javax.swing.JComboBox();
        jButton_refreshAtt = new javax.swing.JButton();
        jTextField_eid = new javax.swing.JTextField();
        jButton_check = new javax.swing.JButton();
        jButton_report = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1260, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_seid.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel_seid.setText("empID");
        getContentPane().add(jLabel_seid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel1_sname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1_sname.setText("name");
        getContentPane().add(jLabel1_sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 610, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 130));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Attendance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 210, 570));

        jLabel5.setText("Employee ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        jButton_oIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_oIn.setText("Open Checkin");
        jButton_oIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_oInActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_oIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 120, 30));

        jButton_cIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_cIn.setText("Close Checkin");
        jButton_cIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cInActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 120, 30));

        jButton_oOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_oOut.setText("Open Checkout");
        jButton_oOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_oOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_oOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 120, 30));

        jButton_cOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_cOut.setText("Close Checkout");
        jButton_cOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 120, 30));

        jLabel6.setText("IN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel8.setText("Out");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jRadioButton_showLeaves.setText("Leaves");
        jRadioButton_showLeaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_showLeavesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_showLeaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 10, 470));

        jLabel9.setText("Employee Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));
        getContentPane().add(jTextField_dateL, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 140, -1));

        jTable_leaves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Leave Date"
            }
        ));
        jTable_leaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_leavesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_leaves);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 280, 100));

        jButton_refreshL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_refreshL.setText("Refresh");
        jButton_refreshL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshLActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refreshL, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        jButton_dateLe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_dateLe.setText("Select");
        jButton_dateLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dateLeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_dateLe, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 70, -1));

        jButton_submitLeave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_submitLeave.setText("Insert");
        jButton_submitLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_submitLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 70, 30));

        jButton_deleteLeave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_deleteLeave.setText("Delete");
        jButton_deleteLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_deleteLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 70, 30));

        jTable_attend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Date", "In Time", "Out Time", "O/T Hours"
            }
        ));
        jScrollPane2.setViewportView(jTable_attend);
        if (jTable_attend.getColumnModel().getColumnCount() > 0) {
            jTable_attend.getColumnModel().getColumn(1).setPreferredWidth(125);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 600, 140));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Search");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabel12.setText("Employee Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, 20));

        jComboBox_empIDL.setToolTipText("");
        getContentPane().add(jComboBox_empIDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 140, -1));

        jButton_searchL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_searchL.setText("Search");
        jButton_searchL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchLActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_searchL, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 70, 30));

        jComboBox_getempSrch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_getempSrch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_getempSrchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_getempSrchMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_getempSrchMousePressed(evt);
            }
        });
        jComboBox_getempSrch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_getempSrchItemStateChanged(evt);
            }
        });
        jComboBox_getempSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_getempSrchActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_getempSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 140, 25));

        jButton_refreshAtt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_refreshAtt.setText("Refresh");
        jButton_refreshAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshAttActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refreshAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));
        getContentPane().add(jTextField_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, -1));

        jButton_check.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_check.setText("Mark");
        jButton_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jButton_report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_report.setText("Report");
        jButton_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 80, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 320, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 320, 10, 140));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 320, 20, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_showLeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_showLeavesActionPerformed
        // TODO add your handling code here:
        if(jRadioButton_showLeaves.isSelected()) {
            jTextField_dateL.setEnabled(true);
            jComboBox_empIDL.setEnabled(true);
            jButton_dateLe.setEnabled(true);
            jButton_deleteLeave.setEnabled(true);
            jButton_submitLeave.setEnabled(true);
            jButton_refreshL.setEnabled(true);
            jButton_searchL.setEnabled(true);
            jTable_leaves.setEnabled(true);
        }
        
        else {
            jTextField_dateL.setEnabled(false);
            jComboBox_empIDL.setEnabled(false);
            jButton_dateLe.setEnabled(false);
            jButton_deleteLeave.setEnabled(false);
            jButton_submitLeave.setEnabled(false);
            jButton_refreshL.setEnabled(false);
            jButton_searchL.setEnabled(false);
            jTable_leaves.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton_showLeavesActionPerformed

    private void jButton_refreshLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshLActionPerformed
        // TODO add your handling code here:
        jTextField_dateL.setText("");
        jComboBox_empIDL.setSelectedIndex(0);
        cleartable();
        readtable();
    }//GEN-LAST:event_jButton_refreshLActionPerformed

    private void jButton_submitLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitLeaveActionPerformed
        Attend att = new Attend();
        String ename = jComboBox_empIDL.getSelectedItem().toString();
        String date = jTextField_dateL.getText().toString();
        
        if(!date.isEmpty()) {
            if(att.submitLeave(ename, date)) {
                jComboBox_empIDL.setSelectedIndex(0);
                jTextField_dateL.setText("");
                JOptionPane.showMessageDialog(null,"Leave recorded successfully");
            }    
            cleartable();
            readtable();
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a date to add the leave");
        }
    }//GEN-LAST:event_jButton_submitLeaveActionPerformed

    private void jTable_leavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_leavesMouseClicked
        // TODO add your handling code here:
        EmployeeInfo ei = new EmployeeInfo();
        int row = jTable_leaves.getSelectedRow();
        String eid = jTable_leaves.getModel().getValueAt(row,0).toString();
        jTextField_dateL.setText(jTable_leaves.getModel().getValueAt(row, 1).toString());
        jComboBox_empIDL.setSelectedItem(ei.getName(eid));
    }//GEN-LAST:event_jTable_leavesMouseClicked

    private void jButton_searchLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchLActionPerformed
        EmployeeInfo ei = new EmployeeInfo();
        try {
            cleartable();
            String ename = jComboBox_empIDL.getSelectedItem().toString();
            String eid = ei.getempID(ename);
            
            String sql = "select * from riyoma.employee_leaves where empID='"+eid+"'";
            
            DefaultTableModel model = (DefaultTableModel) jTable_leaves.getModel();
            
            ResultSet rs = dba.getData(sql);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("date");
                
                model.addRow(new Object[]{d1,d2});             
            }
        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"sql error");
        }
    }//GEN-LAST:event_jButton_searchLActionPerformed

    private void jButton_deleteLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteLeaveActionPerformed
        EmployeeInfo ei = new EmployeeInfo();
        Attend att = new Attend();

        String eid = ei.getempID(jComboBox_empIDL.getSelectedItem().toString());
        String date = jTextField_dateL.getText();
        if(!date.isEmpty()) {
            int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to continue","Warning",0,2);
            if(res == 0) {
                if(att.deleteLeave(eid, date)) {
                    jComboBox_empIDL.setSelectedIndex(0);
                    jTextField_dateL.setText("");
                    JOptionPane.showMessageDialog(null,"Deleted successfully");
                }
            }
            cleartable();
            readtable();
        }
        else {
            JOptionPane.showMessageDialog(null,"Please search a leave and click on the record to delete");
        }
    }//GEN-LAST:event_jButton_deleteLeaveActionPerformed

    private void jButton_refreshAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshAttActionPerformed
        jLabel_seid.setVisible(false);
        jLabel1_sname.setVisible(false);
        clearAttTable();
        readAttTable();
        jComboBox_getempSrch.setSelectedIndex(0);
        jTextField_eid.requestFocus();
        index = 0;
    }//GEN-LAST:event_jButton_refreshAttActionPerformed

    private void jButton_cOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cOutActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to continue","Warning",0,2);
        
        if(res==0) {
        Attend att = new Attend();
        
        att.setOtHours();
        
        jButton_cOut.setEnabled(false);
        
        clearAttTable();
        readAttTable();
        
        jTextField_eid.setEnabled(false);
        jButton_check.setEnabled(false);
        }
    }//GEN-LAST:event_jButton_cOutActionPerformed

    private void jButton_oInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_oInActionPerformed
        jButton_oIn.setEnabled(false);
        jTextField_eid.setEnabled(true);
        jButton_check.setEnabled(true);
        jButton_cIn.setEnabled(true);
        check = 0;
        jTextField_eid.requestFocus();
    }//GEN-LAST:event_jButton_oInActionPerformed

    private void jButton_cInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cInActionPerformed
        // TODO add your handling code here:
        jButton_cIn.setEnabled(false);
        jTextField_eid.setEnabled(false);
        jButton_check.setEnabled(false);
        jButton_oOut.setEnabled(true);
    }//GEN-LAST:event_jButton_cInActionPerformed

    private void jComboBox_getempSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_getempSrchActionPerformed
        // TODO add your handling code here:
        if(index == 1) {
            String search = jComboBox_getempSrch.getSelectedItem().toString();
     
            String sql = "select * from riyoma.attendance a,riyoma.employee e where e.empID=a.empID and e.empName='"+search+"'";
            clearAttTable();
            readSpeRecord(sql);
            index = 0;
        }    
    }//GEN-LAST:event_jComboBox_getempSrchActionPerformed

    private void jComboBox_getempSrchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_getempSrchItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_getempSrchItemStateChanged

    private void jComboBox_getempSrchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_getempSrchMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox_getempSrchMousePressed

    private void jComboBox_getempSrchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_getempSrchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_getempSrchMouseEntered

    private void jButton_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkActionPerformed
        jLabel_seid.setVisible(true);
        jLabel1_sname.setVisible(true);
        EmployeeInfo ei = new EmployeeInfo();
        Attend att = new Attend();
        
        String eid = jTextField_eid.getText();
        if(!eid.isEmpty()) {
            if(ei.empAvailable(eid)) {
                jLabel_seid.setText(eid);
                jLabel1_sname.setText(ei.getName(eid));
                if((check == 0)&&(!att.chkAttend(eid))) {
                    att.markCheckIn(eid);              
                }
                else if(check == 1) {
                    att.markCheckOut(eid);
                }  
                else {
                    JOptionPane.showMessageDialog(null,"ID Error");
                }
                
            }
            else {
                JOptionPane.showMessageDialog(null,"Incorrect ID");
            }
        }
        else {
            JOptionPane.showMessageDialog(null,"No ID scanned");
        }
        
        clearAttTable();
        readAttTable();
        jTextField_eid.setText("");
        jTextField_eid.requestFocus();
    }//GEN-LAST:event_jButton_checkActionPerformed

    private void jButton_oOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_oOutActionPerformed
        // TODO add your handling code here:
        jButton_oOut.setEnabled(false);
        jTextField_eid.setEnabled(true);
        jButton_check.setEnabled(true);
        jButton_cOut.setEnabled(true);
        check = 1;
        jTextField_eid.requestFocus();
    }//GEN-LAST:event_jButton_oOutActionPerformed

    private void jButton_dateLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dateLeActionPerformed
        // TODO add your handling code here:
        DatePicker dp = new DatePicker(this);
        jTextField_dateL.setText(dp.setPickedDate());
    }//GEN-LAST:event_jButton_dateLeActionPerformed

    private void jComboBox_getempSrchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_getempSrchMouseClicked
        // TODO add your handling code here:
        index = 1;
    }//GEN-LAST:event_jComboBox_getempSrchMouseClicked

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
        DBConnManager dbconn = new DBConnManager();
        
        SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy");
        String year = sdf.format(new Date());
        try
        {   
            Connection conn = dbconn.connect();
            JasperDesign jd = JRXmlLoader.load("C:\\\\Management System\\\\src\\\\IReports\\\\Attendance.jrxml");
            String sql = "select a.empID,e.empName,a.month,count(a.empID) as 'Days Present' from riyoma.employee e,riyoma.attendance a where a.date like '"+year+"%' and a.empID=e.empID group by a.empID,a.month";
            
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
           
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp,false); 
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_reportActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });   
    }   

    private void readtable(){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_leaves.getModel();
            
            String query = "select * from riyoma.employee_leaves";
            
            ResultSet rs = dba.getData(query);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("date");
              
                model.addRow(new Object[]{d1,d2});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
    
    private void cleartable(){
        DefaultTableModel dm = (DefaultTableModel)jTable_leaves.getModel();
        for(int i=0;i<dm.getRowCount();i++) {
            for(int j=0;j<dm.getColumnCount();j++) {
                dm.setValueAt("", i, j);
            }
        }     
        dm.setColumnCount(2);
        dm.setRowCount(0);
    }
    
    private void fillLeaveseid() {
        
        jComboBox_empIDL.removeAllItems();
   
        EmployeeInfo ei = new EmployeeInfo();
        ArrayList ename = ei.getEmpName();
        
        Iterator i = ename.iterator();
        
        while(i.hasNext()) {
            jComboBox_empIDL.addItem(i.next());
        }
    }
    
    private void fillEname() {
        
        jComboBox_getempSrch.removeAllItems();
   
        EmployeeInfo ei = new EmployeeInfo();
        ArrayList ename = ei.getEmpName();
        
        Iterator i = ename.iterator();
        
        while(i.hasNext()) {
            jComboBox_getempSrch.addItem(i.next());
        }
    }
    
    private void readAttTable(){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_attend.getModel();
            
            String query = "select * from riyoma.attendance a,riyoma.employee e where e.empID=a.empID";
            
            ResultSet rs = dba.getData(query);
            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("empName");
                String d3 = rs.getString("date");
                String d4 = rs.getString("checkin");
                String d5 = rs.getString("checkout");
                String d6 = rs.getString("otHours");
              
                model.addRow(new Object[]{d1,d2,d3,d4,d5,d6});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
    
    private void readSpeRecord(String sql){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_attend.getModel();
            
            ResultSet rs = dba.getData(sql);
            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("empName");
                String d3 = rs.getString("date");
                String d4 = rs.getString("checkin");
                String d5 = rs.getString("checkout");
                String d6 = rs.getString("otHours");
              
                model.addRow(new Object[]{d1,d2,d3,d4,d5,d6});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
    
    private void clearAttTable(){
        DefaultTableModel dm = (DefaultTableModel)jTable_attend.getModel();
        for(int i=0;i<dm.getRowCount();i++) {
            for(int j=0;j<dm.getColumnCount();j++) {
                dm.setValueAt("", i, j);
            }
        }     
        dm.setColumnCount(6);
        dm.setRowCount(0);
    }
    
    private void control() {
        Attend att = new Attend();;
        
        if(att.dayMarked()) {
            if(att.checkInMarked()) {
                jButton_oOut.setEnabled(true);
            }
            else {
                jButton_oOut.setEnabled(false);
            }
            jButton_cOut.setEnabled(false);
            jButton_cIn.setEnabled(false);
            jButton_oIn.setEnabled(false);
            jTextField_eid.setEnabled(false);
            jButton_check.setEnabled(false);
        } 
        else {
            check = 0;
            jTextField_eid.setEnabled(false);
            jButton_check.setEnabled(false);
            jButton_cIn.setEnabled(false);
            jButton_oIn.setEnabled(true);
            jButton_oOut.setEnabled(false);
            jButton_cOut.setEnabled(false);
        }
    }
    
    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cIn;
    private javax.swing.JButton jButton_cOut;
    private javax.swing.JButton jButton_check;
    private javax.swing.JButton jButton_dateLe;
    private javax.swing.JButton jButton_deleteLeave;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_oIn;
    private javax.swing.JButton jButton_oOut;
    private javax.swing.JButton jButton_refreshAtt;
    private javax.swing.JButton jButton_refreshL;
    private javax.swing.JButton jButton_report;
    private javax.swing.JButton jButton_searchL;
    private javax.swing.JButton jButton_submitLeave;
    private javax.swing.JComboBox jComboBox_empIDL;
    private javax.swing.JComboBox jComboBox_getempSrch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1_sname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_seid;
    private javax.swing.JRadioButton jRadioButton_showLeaves;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_attend;
    private javax.swing.JTable jTable_leaves;
    private javax.swing.JTextField jTextField_dateL;
    private javax.swing.JTextField jTextField_eid;
    // End of variables declaration//GEN-END:variables
}
