/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.EmpMng;

import Data.DBConnManager;
import Data.DB_Access;
import Data.EmployeeInfo;
import data.SalaryInfoData;
import Data.Validator;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gallelaptop.lk
 */
public class Employee extends javax.swing.JFrame {

    DB_Access dba = null;
    Validator valid = null;
    int index = 0;
    
    public Employee() {
        initComponents();
        
        dba = new DB_Access();
        valid = new Validator();
        readtable();
        fillEname();
        fillDesignation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_home = new javax.swing.JButton();
        jButton_salaryInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_eID = new javax.swing.JTextField();
        jTextField_eName = new javax.swing.JTextField();
        jTextField_ePhone = new javax.swing.JTextField();
        jTextField_eAddr = new javax.swing.JTextField();
        jTextField_eEmail = new javax.swing.JTextField();
        jTextField_enic = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_refresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_emp = new javax.swing.JTable();
        jComboBox_desig = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_eid = new javax.swing.JComboBox();
        jButton_demoUp = new javax.swing.JButton();
        jButton_demo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton_report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1264, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, 40, 40));

        jButton_salaryInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_salaryInfo.setText("Salary Info");
        jButton_salaryInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salaryInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salaryInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, 150, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Loan Management");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 210, 150, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 940, 140));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Employee Management");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 154, 220, 570));

        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel10.setText("Phone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel12.setText("Email");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel13.setText("NIC");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 30, -1));

        jLabel15.setText("Designation");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));
        getContentPane().add(jTextField_eID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, -1));
        getContentPane().add(jTextField_eName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, -1));
        getContentPane().add(jTextField_ePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 150, -1));
        getContentPane().add(jTextField_eAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 150, -1));
        getContentPane().add(jTextField_eEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 150, -1));
        getContentPane().add(jTextField_enic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 150, -1));

        jButton_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 100, 40));

        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 100, 40));

        jButton_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 100, 40));

        jButton_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 100, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Search");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jLabel6.setText("Employee Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, 30));

        jTable_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Phone", "Address", "Email", "Designation", "NIC no"
            }
        ));
        jTable_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_emp);
        if (jTable_emp.getColumnModel().getColumnCount() > 0) {
            jTable_emp.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable_emp.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable_emp.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable_emp.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable_emp.getColumnModel().getColumn(4).setPreferredWidth(55);
            jTable_emp.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable_emp.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 870, 130));

        getContentPane().add(jComboBox_desig, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 150, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("eg - 07xxxxxxxx");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, 20));

        jComboBox_eid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_eidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_eidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_eidMouseExited(evt);
            }
        });
        jComboBox_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_eidActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 160, 30));

        jButton_demoUp.setText("Demo u");
        jButton_demoUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_demoUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_demoUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, -1, -1));

        jButton_demo.setText("Demo");
        jButton_demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_demoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_demo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 70, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("add new ");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 20));

        jButton_report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_report.setText("Report");
        jButton_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        // TODO add your handling code here:
        jButton_add.setEnabled(true);
        jTextField_eID.setEnabled(true);
        jButton_delete.setEnabled(true);
        jButton_update.setEnabled(true);
        jTextField_eAddr.setText("");
        jTextField_eEmail.setText("");
        jTextField_eID.setText("");
        jTextField_eName.setText("");
        jTextField_ePhone.setText("");
        jTextField_enic.setText("");
        jComboBox_desig.setSelectedIndex(0);
        index = 0;
        cleartable();
        readtable(); 
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        EmployeeInfo ei = new EmployeeInfo();
        
        String eid = jTextField_eID.getText();
        String ename = jTextField_eName.getText();
        String phone = jTextField_ePhone.getText();
        String address = jTextField_eAddr.getText();
        String email = jTextField_eEmail.getText();
        String desig = jComboBox_desig.getSelectedItem().toString();
        String nic = jTextField_enic.getText();
        char arr[] = {'a','b','c','d','1','2','3','4'}; 
        String password = ei.getRandomString(8,arr);
        
        if(!empty(eid, ename, phone, address, email, nic, password)) {
            if(valid.isNumber(phone)&&(phone.length())==10) {
                if(valid.isText(ename)) {
                    if((eid.length()==4)&&(!ei.empAvailable(eid))) {
                        if(valid.checkEmail(email)) {
                            if(nic.length()==10&&nic.endsWith("v")&&valid.isNumber(nic.substring(0,9))) {
                                if(password.length()==8) {
        try {
            int phon = Integer.parseInt(phone);
            
            String sql = "insert into riyoma.employee values('"+eid+"','"+ename+"',"+phon+",'"+address+"','"+email+"','"+desig+"','"+nic+"','"+password+"')";
            
            dba.setData(sql);
            JOptionPane.showMessageDialog(null,"Employee added suuccessfully");
            
            /*try {
                ei.sendMail(email, password);
            } catch (MessagingException ex) {
                System.out.println(ex);
            }*/
            
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Insertion failed");
            
        }
        
  
        cleartable();
        readtable();
        fillDesignation();
        fillEname();
        
        jTextField_eAddr.setText("");
        jTextField_eEmail.setText("");
        jTextField_eID.setText("");
        jTextField_eName.setText("");
        jTextField_ePhone.setText("");
        jTextField_enic.setText("");
        jComboBox_desig.setSelectedIndex(0);
                                }
                                else {
                                    JOptionPane.showMessageDialog(null, "Enter a password with 8 characters");
                                }
                            }
                            else {
                                JOptionPane.showMessageDialog(null, "Invalid NIC number");
                            }                                
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Invalid email format");
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Invalid employee ID");
                    }                        
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid name");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Invalid phone number");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        
        String eid = jTextField_eID.getText();
        String ename = jTextField_eName.getText();
        String phone = jTextField_ePhone.getText();
        String address = jTextField_eAddr.getText();
        String email = jTextField_eEmail.getText();
        String desig = jComboBox_desig.getSelectedItem().toString();
        String nic = jTextField_enic.getText();
        
        if(!emptyNew(eid, ename, phone, address, email, nic)) {
            if(valid.isNumber(phone)&&(phone.length())==10) {
                if(valid.isText(ename)) {
                    if(eid.length()==4) {
                        if(valid.checkEmail(email)) {
                            if(nic.length()==10&&nic.endsWith("v")&&valid.isNumber(nic.substring(0,9))) {
        try {
            // TODO add your handling code here:   
            int phon = Integer.parseInt(phone);
            
            String sql = "update riyoma.employee set empName='"+ename+"',phone="+phon+",address='"+address+"',email='"+email+"',designation='"+desig+"',nic='"+nic+"' where empID='"+eid+"'";
            
            dba.setData(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"update query failed");
        }
        
        cleartable();
        readtable();
        JOptionPane.showMessageDialog(null,"successful update");
        
        jTextField_eAddr.setText("");
        jTextField_eEmail.setText("");
        jTextField_eID.setText("");
        jTextField_eName.setText("");
        jTextField_ePhone.setText("");
        jTextField_enic.setText("");
        jComboBox_desig.setSelectedIndex(0);
        
                            }
                            else {
                                JOptionPane.showMessageDialog(null, "Invalid NIC number");
                            }                                
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Invalid email format");
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Invalid employee ID");
                    }                        
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid name");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Invalid phone number");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please search an employee and click on the record to update");
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTable_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_empMouseClicked
        // TODO add your handling code here:
        index = 0;
        jButton_add.setEnabled(false);
        jButton_delete.setEnabled(true);
        jButton_update.setEnabled(true);
        jTextField_eID.setEnabled(false);
        int row  = jTable_emp.getSelectedRow();
        jTextField_eID.setText(jTable_emp.getModel().getValueAt(row, 0).toString());
        jTextField_eName.setText(jTable_emp.getModel().getValueAt(row, 1).toString());
        jTextField_ePhone.setText(jTable_emp.getModel().getValueAt(row, 2).toString());
        jTextField_eAddr.setText(jTable_emp.getModel().getValueAt(row, 3).toString());
        jTextField_eEmail.setText(jTable_emp.getModel().getValueAt(row, 4).toString());
        jComboBox_desig.setSelectedItem(jTable_emp.getModel().getValueAt(row, 5));
        jTextField_enic.setText(jTable_emp.getModel().getValueAt(row, 6).toString());      
    }//GEN-LAST:event_jTable_empMouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        
        String eid = jTextField_eID.getText();
        
        if(!eid.isEmpty()) {
            int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to continue","Warning",0,2);
            if(res == 0) {
                try {
                    String sql = "delete from riyoma.employee where empID='"+eid+"'";
                    dba.setData(sql);

                    JOptionPane.showMessageDialog(null,"successful delete");
            
                } catch (SQLException ex) {
                    System.out.println(ex); 
                }
            }    
        
        jTextField_eAddr.setText("");
        jTextField_eEmail.setText("");
        jTextField_eID.setText("");
        jTextField_eName.setText("");
        jTextField_ePhone.setText("");
        jTextField_enic.setText("");
        jComboBox_desig.setSelectedIndex(0);
        }
        else {
            JOptionPane.showMessageDialog(null,"Please search an employee and click on the record to delete");
        }
        
        cleartable();
        readtable();
        fillEname();
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        new Loan().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_salaryInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salaryInfoActionPerformed
        close();
        new SalaryInfo().setVisible(true);
    }//GEN-LAST:event_jButton_salaryInfoActionPerformed

    private void jButton_demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_demoActionPerformed
        // TODO add your handling code here:
        jTextField_eID.setText("e010");
        jTextField_eName.setText("Sheetal Vishwanathan");
        jTextField_ePhone.setText("0773378667");
        jTextField_eAddr.setText("Malabe");
        jTextField_eEmail.setText("sheetaltest@gmail.com");
        jComboBox_desig.setSelectedItem("Receptionist");
        jTextField_enic.setText("916545673v");
    }//GEN-LAST:event_jButton_demoActionPerformed

    private void jButton_demoUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_demoUpActionPerformed
        // TODO add your handling code here:
        jTextField_eID.setText("e011");
        jTextField_eName.setText("Vahid Ghelijkhani");
        jTextField_ePhone.setText("0774478557");
        jTextField_eAddr.setText("Colombo 09");
        jTextField_eEmail.setText("vahidtest@gmail.com");
        jComboBox_desig.setSelectedItem("Finance Manager");
        jTextField_enic.setText("946542273v");
    }//GEN-LAST:event_jButton_demoUpActionPerformed

    private void jComboBox_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_eidActionPerformed
        // TODO add your handling code here:
        if(index == 1) {
            String search = jComboBox_eid.getSelectedItem().toString();
            String sql = "select * from riyoma.employee where empName='"+search+"'";
            cleartable();
            readSpeRecord(sql);
            jButton_delete.setEnabled(false);
            jButton_update.setEnabled(false);
            index = 0;
        }
    }//GEN-LAST:event_jComboBox_eidActionPerformed

    private void jComboBox_eidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_eidMouseEntered

    }//GEN-LAST:event_jComboBox_eidMouseEntered

    private void jComboBox_eidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_eidMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_eidMouseExited

    private void jComboBox_eidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_eidMouseClicked
        index = 1;
    }//GEN-LAST:event_jComboBox_eidMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        close();
        new SalaryInfo().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
        DBConnManager dbconn = new DBConnManager();
        try
        {   
            Connection conn = dbconn.connect();
            JasperDesign jd = JRXmlLoader.load("E:\\\\PROJECT\\\\Riyoma System\\\\src\\\\IReports\\\\Employee.jrxml");
            String sql = "select empID,empName,phone,address,email,designation,nic from riyoma.employee";
            
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
           
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp,false); 
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_reportActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }
    
    private void readtable(){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_emp.getModel();
            
            String query = "select * from riyoma.employee";
            
            ResultSet rs = dba.getData(query);
            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("empName");
                String d3 = rs.getString("phone");
                String d4 = rs.getString("address");
                String d5 = rs.getString("email");
                String d6 = rs.getString("designation");
                String d7 = rs.getString("nic");
              
                model.addRow(new Object[]{d1,d2,d3,d4,d5,d6,d7});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
    
    private void readSpeRecord(String sql){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_emp.getModel();
            
            ResultSet rs = dba.getData(sql);
            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("empName");
                String d3 = rs.getString("phone");
                String d4 = rs.getString("address");
                String d5 = rs.getString("email");
                String d6 = rs.getString("designation");
                String d7 = rs.getString("nic");
              
                model.addRow(new Object[]{d1,d2,d3,d4,d5,d6,d7});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
    
    private void cleartable(){
        DefaultTableModel dm = (DefaultTableModel)jTable_emp.getModel();
        for(int i=0;i<dm.getRowCount();i++) {
            for(int j=0;j<dm.getColumnCount();j++) {
                dm.setValueAt("", i, j);
            }
        }     
        dm.setColumnCount(7);
        dm.setRowCount(0);
    }
    
    private void fillDesignation() {
        jComboBox_desig.removeAllItems();
   
        SalaryInfoData sid = new SalaryInfoData();
        ArrayList desig = sid.getDesignation();
        
        Iterator i = desig.iterator();
        
        while(i.hasNext()) {
                jComboBox_desig.addItem(i.next());
        }
    }
    
    private boolean empty(String a, String b,String c, String d, String e, String f,String g) {
        boolean result = true;
        if(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty()||e.isEmpty()||f.isEmpty()||g.isEmpty()) {
            return result;
        }
        else
            return result = false;
    }
    
    private boolean emptyNew(String a, String b,String c, String d, String e, String f) {
        boolean result = true;
        if(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty()||e.isEmpty()||f.isEmpty()) {
            return result;
        }
        else
            return result = false;
    }
    
    private void fillEname() {
        
        jComboBox_eid.removeAllItems();
   
        EmployeeInfo ei = new EmployeeInfo();
        ArrayList ename = ei.getEmpName();
        
        Iterator i = ename.iterator();
        
        while(i.hasNext()) {
            jComboBox_eid.addItem(i.next());
        }
    }
    
    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_demo;
    private javax.swing.JButton jButton_demoUp;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_report;
    private javax.swing.JButton jButton_salaryInfo;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox jComboBox_desig;
    private javax.swing.JComboBox jComboBox_eid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_emp;
    private javax.swing.JTextField jTextField_eAddr;
    private javax.swing.JTextField jTextField_eEmail;
    private javax.swing.JTextField jTextField_eID;
    private javax.swing.JTextField jTextField_eName;
    private javax.swing.JTextField jTextField_ePhone;
    private javax.swing.JTextField jTextField_enic;
    // End of variables declaration//GEN-END:variables
}
