/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.EmpMng;

import Data.DB_Access;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gallelaptop.lk
 */
public class Login extends javax.swing.JFrame {

    DB_Access dba = null;
    private int count = 0;

    public Login() {
        initComponents();

        dba = new DB_Access();
        jTxtfld_usrname.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTxtfld_usrname = new javax.swing.JTextField();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jbtn_signin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employee.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 260, 230));

        jTxtfld_usrname.setBackground(new java.awt.Color(204, 255, 204));
        jTxtfld_usrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtfld_usrnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtfld_usrname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 190, 30));

        jPasswordField_pass.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 190, 30));

        jbtn_signin.setBackground(new java.awt.Color(204, 255, 204));
        jbtn_signin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_signin.setText("Login");
        jbtn_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_signinActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 100, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please Login to continue");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        jLabel1.setAlignmentY(0.4F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 920, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 710));
        jLabel2.setMinimumSize(new java.awt.Dimension(1920, 700));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 710));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtfld_usrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtfld_usrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtfld_usrnameActionPerformed

    private void jPasswordField_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passActionPerformed

    private void jbtn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_signinActionPerformed

        String password = jPasswordField_pass.getText();
        String username = jTxtfld_usrname.getText();

        try {
            // TODO add your handling code here:

            String sql = "select * from riyoma.employee where empID='" + username + "' and password='" + password + "'";

            ResultSet rs = dba.getData(sql);

            if (rs.next()) {
                //JOptionPane.showMessageDialog(null,"Login details are correct");
                count = 0;
                String desig = rs.getString(6);

                if (desig.equals("MD") || desig.equals("CEO")) {
                    //if (desig.equals("MD / CEO")) {
                        new Home().setVisible(true);
                    } else if (desig.equals("HR Manager") || desig.equals("Finance Manager")) {
                        new ManagerHome().setVisible(true);
                    } else if (desig.equals("Receptionist")) {
                        new ReceptionistHome().setVisible(true);
                    }
                    close();
                } else {
                    JOptionPane.showMessageDialog(null, "Login details are incorrect");
                    count++;

                    if (count == 3) {
                        jbtn_signin.setEnabled(false);
                        jTxtfld_usrname.setEnabled(false);
                        jPasswordField_pass.setEnabled(false);
                        JOptionPane.showMessageDialog(null, "You entered incorrect login details three times. Try again in 15s");
                        try {
                            Thread.sleep(15000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        jbtn_signin.setEnabled(true);
                        jTxtfld_usrname.setEnabled(true);
                        jPasswordField_pass.setEnabled(true);
                        count = 0;
                    }
                }
            }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtn_signinActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JTextField jTxtfld_usrname;
    private javax.swing.JButton jbtn_signin;
    // End of variables declaration//GEN-END:variables
}
