/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.EmpMng;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Data.DB_Access;
import data.SalaryCalc;
import Data.Validator;
import Data.loanInfo;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author gallelaptop.lk
 */
public class Salary extends javax.swing.JFrame {

    DB_Access dba = null;
    Validator valid = null;
    private String salaryID = "";
    
    public Salary() {
        initComponents();
        
        dba = new DB_Access();
        valid = new Validator();
        
        readtable();
        readEmpTable();
        
        //disable editing of emp text fields
        jTextField_eid.setEnabled(false);
        jTextField_ename.setEnabled(false);
        jTextField_desig.setEnabled(false);
        
        //disable editing of ot,loan fields
        jTextField_OT.setEnabled(false);
        jTextField_loanR.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_home = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_eid = new javax.swing.JTextField();
        jTextField_ename = new javax.swing.JTextField();
        jTextField_desig = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_emp = new javax.swing.JTable();
        jTextField_bonus = new javax.swing.JTextField();
        jTextField_OT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_loanR = new javax.swing.JTextField();
        jButton_calcSal = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_refresh = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel_showSal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_sal = new javax.swing.JTable();
        jButton_search = new javax.swing.JButton();
        jButton_demo = new javax.swing.JButton();
        jButton_payslip = new javax.swing.JButton();
        jButton_report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1260, 700));
        setPreferredSize(new java.awt.Dimension(1260, 710));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_home.setBackground(new java.awt.Color(0, 153, 204));
        jButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home1.png"))); // NOI18N
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 610, 40, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Salary Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, 150, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 970, 140));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Salary Calculation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 210, 570));

        jLabel8.setText("Bonus Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel5.setText("O/T Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel7.setText("Employee ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel9.setText("Employee Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel10.setText("Designation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jTextField_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_eidActionPerformed(evt);
            }
        });
        jTextField_eid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_eidFocusGained(evt);
            }
        });
        jTextField_eid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_eidInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(jTextField_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));
        getContentPane().add(jTextField_ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, -1));
        getContentPane().add(jTextField_desig, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, -1));

        jTable_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Employee Name", "Designation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_emp);
        if (jTable_emp.getColumnModel().getColumnCount() > 0) {
            jTable_emp.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_emp.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable_emp.getColumnModel().getColumn(2).setPreferredWidth(35);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 370, 110));

        jTextField_bonus.setText("0");
        getContentPane().add(jTextField_bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 130, -1));

        jTextField_OT.setText("0");
        getContentPane().add(jTextField_OT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 130, -1));

        jLabel11.setText("Loan Reductions");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jTextField_loanR.setText("0");
        getContentPane().add(jTextField_loanR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, -1));

        jButton_calcSal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_calcSal.setText("Calculate");
        jButton_calcSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcSalActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_calcSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 110, 40));

        jButton_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 110, 40));

        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 110, 40));

        jButton_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 110, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("Total Salary = Rs.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 180, 40));

        jLabel_showSal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_showSal.setText("0.00");
        getContentPane().add(jLabel_showSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 90, 40));

        jTable_sal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SalaryID", "EmployeeID", "Month", "Date Paid", "Bonus Amount", "OT Amount", "Reductions", "Total Salary"
            }
        ));
        jTable_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_salMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_sal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 750, 170));

        jButton_search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 110, 40));

        jButton_demo.setText("Demo");
        jButton_demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_demoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_demo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 70, 20));

        jButton_payslip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_payslip.setText("Pay Slip");
        jButton_payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_payslipActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_payslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 110, 40));

        jButton_report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_report.setText("Report");
        jButton_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
         
        jTable_emp.setVisible(true);
        jButton_delete.setEnabled(true);
        jButton_update.setEnabled(true);
        
        jTextField_OT.setText("0");
        jTextField_bonus.setText("0");
        jTextField_desig.setText("");
        jTextField_eid.setText("");
        jTextField_ename.setText("");
        jTextField_loanR.setText("0");
        salaryID = "";
        jLabel_showSal.setText("0.00");
        jButton_calcSal.setEnabled(true);
        
        cleartable();
        readtable();
        cleartableEmp();
        readEmpTable();
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jTable_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_empMouseClicked
        // TODO add your handling code here:
        SalaryCalc sc = new SalaryCalc();
        
        jButton_update.setEnabled(false);
        jButton_delete.setEnabled(false);

        int row = jTable_emp.getSelectedRow();
        String eid = jTable_emp.getModel().getValueAt(row, 0).toString();
        String ename = jTable_emp.getModel().getValueAt(row, 1).toString();
        String desig = jTable_emp.getModel().getValueAt(row, 2).toString();
        
        if(sc.checkSalary(eid)){
            jButton_calcSal.setEnabled(false);
            jTextField_OT.setText("0");
            JOptionPane.showMessageDialog(null,"Salary payment has already been made for current month");
        }
        else {
            jButton_calcSal.setEnabled(true);
            jTextField_OT.setText(String.valueOf(sc.getOtAmount(eid, desig)));
            jTextField_loanR.setText(String.valueOf(sc.getloanAmount(eid)));
        }
        
        jTextField_eid.setText(eid);
        jTextField_ename.setText(ename);
        jTextField_desig.setText(desig);
        
    }//GEN-LAST:event_jTable_empMouseClicked

    private void jTable_salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_salMouseClicked
        // TODO add your handling code here:
        jButton_calcSal.setEnabled(false);
        jButton_delete.setEnabled(true);
        jButton_update.setEnabled(true);
        jTable_emp.setVisible(false);
        
        int row = jTable_sal.getSelectedRow();
        salaryID = jTable_sal.getModel().getValueAt(row, 0).toString();
        jTextField_eid.setText(jTable_sal.getModel().getValueAt(row, 1).toString());
        jTextField_bonus.setText(jTable_sal.getModel().getValueAt(row, 4).toString());
        jTextField_OT.setText(jTable_sal.getModel().getValueAt(row, 5).toString());
        jTextField_loanR.setText((jTable_sal.getModel().getValueAt(row, 6).toString()));
    }//GEN-LAST:event_jTable_salMouseClicked

    private void jButton_calcSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcSalActionPerformed
        
        SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(new Date());
        
        String yearMonth = date.substring(0,7);
        
        SalaryCalc sc = new SalaryCalc();
        loanInfo lf = new loanInfo();
        
        //String month = jComboBox_month.getSelectedItem().toString();
        String otA  = jTextField_OT.getText();
        String bonus = jTextField_bonus.getText();
        String loan = jTextField_loanR.getText();
        String empID = jTextField_eid.getText();
        String desig = jTextField_desig.getText();
        String month = sc.getMonth();
        
        if(!empty(otA, bonus, loan, empID, desig)) {
            if(valid.isNumber(bonus)) {
        try {
            // TODO add your handling code here: 
            double otAmount = Double.parseDouble(otA);
            double bonuses = Double.parseDouble(bonus);
            double loanR = Double.parseDouble(loan);
            
            double total = sc.calculate(empID, bonuses, otAmount, loanR);
            
            String tot = String.valueOf(total);
            jLabel_showSal.setText(tot);
            
            String sql = "insert into riyoma.salary(empID,bonuses,otAmount,loanReductions,totalSalary,date,month) values('"+empID+"',"+bonuses+","+otAmount+","+loanR+","+total+",'"+date+"','"+month+"')";
            
            dba.setData(sql);
            
            if(loanR > 0) {
                int loanID = lf.getLoanID(empID, yearMonth);
               
                double amount = loanR;
                
                sc.setleftToPay(loanID, amount);
            }
            
            JOptionPane.showMessageDialog(null,"Payment made successfully!");
            
            int res = JOptionPane.showConfirmDialog(null,"Print the pay slip","Info",0,1);
            if(res == 0) {
                sc.autoGenPaySlip(empID, date);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"insert query failed");
        }
        
            //jComboBox_month.setSelectedIndex(0);
            jTextField_OT.setText("0");
            jTextField_bonus.setText("0");
            jTextField_loanR.setText("0");
        
            cleartable();
            readtable();
            cleartableEmp();
            readEmpTable();
            }
            else {
                JOptionPane.showMessageDialog(null, "Numeric value should be entered to Bonus Amount, O/T Amount and Loan Reductions");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select an employee and fill all the fields");
        }
    }//GEN-LAST:event_jButton_calcSalActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
       
        if(!salaryID.equals("")) {
            int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to continue","Warning",0,2);
            if(res == 0) {
                try {
                    String sql = "delete from riyoma.salary where salaryID="+salaryID+"";
            
                    dba.setData(sql);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }

                jTextField_OT.setText("0");
                jTextField_bonus.setText("0");
                jTextField_loanR.setText("0");        
        
                salaryID = "";
                JOptionPane.showMessageDialog(null,"Successul deletion");
            }
        }
        else {
            JOptionPane.showMessageDialog(null,"Please search an employee and click on the record to delete");
        }
                
        cleartable();
        readtable();
        cleartableEmp();
        readEmpTable();
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        
                    
        jTextField_OT.setEditable(false);
        jTextField_loanR.setEditable(false);
        
        String empID = jTextField_eid.getText();
        
        if(!empID.isEmpty()) {
        String sql = "select * from riyoma.salary where empID='"+empID+"'";
        cleartable();
        readSpeRecord(sql);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select an employee");
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        
        SalaryCalc sc = new SalaryCalc();
            
        String otA  = jTextField_OT.getText();
        String bonus = jTextField_bonus.getText();
        String loan = jTextField_loanR.getText();
        String empID = jTextField_eid.getText();
        
        if(!empty(otA, bonus, loan, empID)) {
            if(valid.isNumber(bonus)) {
        try {
            
            double otAmount = Double.parseDouble(otA);
            double bonuses = Double.parseDouble(bonus);
            double loanR = Double.parseDouble(loan);
            
            double total = sc.calculate(empID, bonuses, otAmount, loanR);
            
            String tot = String.valueOf(total);
            jLabel_showSal.setText(tot);
            
            String sql = "update riyoma.salary set bonuses="+bonuses+",totalSalary="+total+" where salaryID='"+salaryID+"'";
            
            dba.setData(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"update query failed");
        }
        
        
        
        jTextField_OT.setText("0");
        jTextField_bonus.setText("0");
        jTextField_loanR.setText("0");
        
        cleartable();
        readtable();
        cleartableEmp();
        readEmpTable();
        
        salaryID = "";
        JOptionPane.showMessageDialog(null,"Payment updated successfully!");
            }
            else {
                JOptionPane.showMessageDialog(null, "Numeric value should be entered to Bonus");
            }                
        }
        else {
            JOptionPane.showMessageDialog(null,"Please search an employee and click on the record to update ");
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        new SalaryInfo().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_demoActionPerformed
        jTextField_bonus.setText("2000");
    }//GEN-LAST:event_jButton_demoActionPerformed

    private void jTextField_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_eidActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jTextField_eidActionPerformed

    private void jTextField_eidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_eidInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_eidInputMethodTextChanged

    private void jTextField_eidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_eidFocusGained
        // TODO add your hanling code here:
    }//GEN-LAST:event_jTextField_eidFocusGained

    private void jButton_payslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_payslipActionPerformed
        // TODO add your handling code here:
        SalaryCalc sc = new SalaryCalc();
        if(salaryID.equals("")) {
            JOptionPane.showMessageDialog(null,"Please select a salary record to generate the pay slip");
        }
        else {
            sc.generatePaySlip(salaryID);
            salaryID = "";
        }
    }//GEN-LAST:event_jButton_payslipActionPerformed

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
        // TODO add your handling code here:
        SalaryCalc sc = new SalaryCalc();
        sc.generateReport();
    }//GEN-LAST:event_jButton_reportActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }
    
     private void readtable(){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_sal.getModel();
            
            String query = "select * from riyoma.salary";
            
            
            //JOptionPane.showMessageDialog(null,query1);
            
            ResultSet rs = dba.getData(query);

            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("salaryID");
                String d2 = rs.getString("empID");
                String d3 = rs.getString("bonuses");
                String d4 = rs.getString("otAmount");
                String d5 = rs.getString("loanReductions");
                String d6 = rs.getString("totalSalary");
                String d7 = rs.getString("date");
                String d8 = rs.getString("month");
              
                model.addRow(new Object[]{d1,d2,d8,d7,d3,d4,d5,d6});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
     
    private void readSpeRecord(String sql){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_sal.getModel();           
            
            
            //JOptionPane.showMessageDialog(null,query1);
            
            ResultSet rs = dba.getData(sql);

            //JOptionPane.showMessageDialog(null,rs1);
            while(rs.next())
            {
                String d1 = rs.getString("salaryID");
                String d2 = rs.getString("empID");
                String d3 = rs.getString("bonuses");
                String d4 = rs.getString("otAmount");
                String d5 = rs.getString("loanReductions");
                String d6 = rs.getString("totalSalary");
                String d7 = rs.getString("date");
                String d8 = rs.getString("month");

              
                model.addRow(new Object[]{d1,d2,d8,d7,d3,d4,d5,d6});             
            }
        } catch (SQLException ex) {
           System.out.println(ex + "-----------Select query failed");
        } 
    }
     
    private void readEmpTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable_emp.getModel();
            
            String query = "select empID,empName,designation from riyoma.employee";
            
            ResultSet rs = dba.getData(query);
            
            while(rs.next()) {
                String d1 = rs.getString("empID");
                String d2 = rs.getString("empName");
                String d3 = rs.getString("designation");
                
                dtm.addRow(new Object[]{d1,d2,d3});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex + "-----------Select query failed");
        }
    } 
    
    private void cleartable(){
        DefaultTableModel dm = (DefaultTableModel)jTable_sal.getModel();
        for(int i=0;i<dm.getRowCount();i++) {
            for(int j=0;j<dm.getColumnCount();j++) {
                dm.setValueAt("", i, j);
            }
        }     
        dm.setColumnCount(8);
        dm.setRowCount(0);
    }
    
    private void cleartableEmp(){
        DefaultTableModel dm = (DefaultTableModel)jTable_emp.getModel();
        for(int i=0;i<dm.getRowCount();i++) {
            for(int j=0;j<dm.getColumnCount();j++) {
                dm.setValueAt("", i, j);
            }
        }     
        dm.setColumnCount(3);
        dm.setRowCount(0);
    }
    
    private boolean empty(String a, String b,String c, String d, String e) {
        boolean result = true;
        if(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty()||e.isEmpty()) {
            return result;
        }
        else
            return result = false;
    }
    
    private boolean empty(String a, String b,String c, String d) {
        boolean result = true;
        if(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty()) {
            return result;
        }
        else
            return result = false;
    }
    
    public void close(){  
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_calcSal;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_demo;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_payslip;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_report;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_showSal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_emp;
    private javax.swing.JTable jTable_sal;
    private javax.swing.JTextField jTextField_OT;
    private javax.swing.JTextField jTextField_bonus;
    private javax.swing.JTextField jTextField_desig;
    private javax.swing.JTextField jTextField_eid;
    private javax.swing.JTextField jTextField_ename;
    private javax.swing.JTextField jTextField_loanR;
    // End of variables declaration//GEN-END:variables
}
